#!/usr/bin/env python3
"""Grounded Marp slide artifacts and deterministic linting for Mary papers."""

from __future__ import annotations

from html import unescape
from html.parser import HTMLParser
import json
from pathlib import Path, PurePosixPath
import re
import shutil
import subprocess
import tempfile
from typing import Any

from mw_paper_artifacts import (
    SLIDES_CONTEXT_FILE,
    SOURCE_LOCATOR_FILE,
    artifact_path,
    resolve_artifact_path,
)
from mw_paper_locators import SourceLocatorError, validate_source_locator_index
from mw_paper_sources import sha256_file
from mw_paper_summary import (
    PaperSummaryError,
    SUMMARY_FILE,
    SUMMARY_LEDGER_FILE,
    load_summary_ledger,
    validate_summary,
)
from mw_runtime import atomic_write_text


SLIDES_CONTEXT_SCHEMA = 1
SLIDES_FILE = "slides.md"
FIGURES_DIR = "figures"
PAPER_MAKEFILE = "Makefile"
HYPO_PREVIEW_DIR = "hypo-template-preview"
HYPO_PREVIEW_FILE = f"{HYPO_PREVIEW_DIR}/Slide.tex"
PAPER_MAKEFILE_MARKER = "# mary-paper-build:v1"
RESEARCH_MAKEFILE = Path(".mary-research") / "Makefile"
RESEARCH_MAKEFILE_MARKER = "# mary-research-build:v1"
THEME_NAME = "mary-shanghaitech-red"
PLUGIN_ROOT = Path(__file__).resolve().parents[1]
THEME_PATH = PLUGIN_ROOT / "assets" / "marp" / "themes" / f"{THEME_NAME}.css"
MARP_CONFIG_PATH = PLUGIN_ROOT / "assets" / "marp" / "marp.config.mjs"
PROJECT_THEME_RELATIVE = Path(".mary-research") / "marp" / "themes" / f"{THEME_NAME}.css"
VSCODE_SETTINGS_RELATIVE = Path(".vscode") / "settings.json"
VSCODE_THEME_REFERENCE = f"./{PROJECT_THEME_RELATIVE.as_posix()}"

REQUIRED_FRONTMATTER = {
    "marp": "true",
    "theme": THEME_NAME,
    "size": "16:9",
    "math": "katex",
    "paginate": "true",
}
SECTION_ORDER = ("background", "method", "experiments", "takeaways")
SECTION_PREFIXES = {"background": "B", "method": "M", "experiments": "E"}
LAYOUT_CLASSES = {
    "cols-2",
    "cols-2-73",
    "cols-2-64",
    "cols-2-37",
    "cols-2-46",
    "cols-3",
    "rows-2",
    "rows-2-73",
    "rows-2-64",
    "rows-2-55",
    "rows-2-37",
    "rows-2-28",
    "pin-3",
}
IMAGE_PANEL_CLASSES = {"limg", "mimg", "rimg", "timg", "bimg"}
STRUCTURAL_CLASSES = {"trans", "toc_a", "toc_b"}
MAX_PAGES = 24
MAX_VISIBLE_CHARACTERS = 900
MAX_VISIBLE_LINES = 36
MAX_LIST_ITEMS = 8
MAX_CODE_LINES = 14

PAPER_MAKEFILE_TEMPLATE = r'''# mary-paper-build:v1
# Generated by Mary Workflow. The existing slides.md is never rewritten by these targets.

PROJECT_ROOT := $(abspath $(CURDIR)/../../..)
SLIDES := slides.md
BUILD_DIR ?= build
THEME := $(PROJECT_ROOT)/.mary-research/marp/themes/mary-shanghaitech-red.css
MARP ?= npx @marp-team/marp-cli@4.3.1
HYPO_PATH ?= $(PROJECT_ROOT)/../Hypoxanthine-LaTeX
HYPO_PREVIEW := hypo-template-preview/Slide.tex

.PHONY: slide slides slide-html slide-pptx hypo-template clean

slide slides: $(BUILD_DIR)/slides.pdf

$(BUILD_DIR)/slides.pdf: $(SLIDES) $(THEME)
	@mkdir -p "$(BUILD_DIR)"
	$(MARP) "$(SLIDES)" --theme-set "$(THEME)" --pdf --allow-local-files -o "$@"

slide-html: $(BUILD_DIR)/slides.html

$(BUILD_DIR)/slides.html: $(SLIDES) $(THEME)
	@mkdir -p "$(BUILD_DIR)"
	$(MARP) "$(SLIDES)" --theme-set "$(THEME)" --html --allow-local-files -o "$@"

slide-pptx: $(BUILD_DIR)/slides.pptx

$(BUILD_DIR)/slides.pptx: $(SLIDES) $(THEME)
	@mkdir -p "$(BUILD_DIR)"
	$(MARP) "$(SLIDES)" --theme-set "$(THEME)" --pptx --allow-local-files -o "$@"

# Compile a separate, original Hypoxanthine-LaTeX preview for visual comparison.
# This target never changes slides.md or build/slides.pdf.
hypo-template: $(BUILD_DIR)/hypo-template-preview.pdf

$(BUILD_DIR)/hypo-template-preview.pdf: $(HYPO_PREVIEW)
	@test -f "$(HYPO_PATH)/make/Hypoxanthine.mk" || (echo "Set HYPO_PATH to the Hypoxanthine-LaTeX checkout."; exit 2)
	$(MAKE) -f "$(HYPO_PATH)/make/Hypoxanthine.mk" HYPO_PATH="$(HYPO_PATH)" NAME=hypo-template-preview MAIN_FILE="$(CURDIR)/$(HYPO_PREVIEW)" OUT_DIR="$(CURDIR)/$(BUILD_DIR)/hypo-template-preview" SHELL_ESCAPE=1 all
	cp "$(BUILD_DIR)/hypo-template-preview/Slide.pdf" "$@"

clean:
	rm -rf "$(BUILD_DIR)"
'''

RESEARCH_MAKEFILE_TEMPLATE = r'''# mary-research-build:v1
# Generated by Mary Workflow. This dispatcher never rewrites any paper artifact.

RESEARCH_ROOT := $(abspath $(CURDIR))
PAPER_DIRS := $(wildcard $(RESEARCH_ROOT)/papers/*)
PAPER_IDS := $(notdir $(PAPER_DIRS))
PAPER_ID ?= $(firstword $(PAPER_IDS))
PAPER_DIR := $(RESEARCH_ROOT)/papers/$(PAPER_ID)

.PHONY: slide slides slide-html slide-pptx hypo-template clean check

slide: check
	$(MAKE) -C "$(PAPER_DIR)" slide

slides: slide

slide-html: check
	$(MAKE) -C "$(PAPER_DIR)" slide-html

slide-pptx: check
	$(MAKE) -C "$(PAPER_DIR)" slide-pptx

hypo-template: check
	$(MAKE) -C "$(PAPER_DIR)" hypo-template

clean: check
	$(MAKE) -C "$(PAPER_DIR)" clean

check:
	@test -n "$(PAPER_ID)" || (echo "No paper workspace found under $(RESEARCH_ROOT)/papers."; exit 2)
	@test -d "$(PAPER_DIR)" || (echo "Unknown PAPER_ID=$(PAPER_ID); use make PAPER_ID=<paper-id> slide."; exit 2)
'''

HYPO_PREVIEW_TEMPLATE = r'''\documentclass[theme=school, aspectratio=169]{Hypo-Slide}

\HypoSlideSetup{
  title={GaussianFluent},
  subtitle={Original Hypoxanthine-LaTeX template preview},
  author={Bei Huang et al.},
  institute={ShanghaiTech University},
  date={2026}
}

\begin{document}

\frame{\titlepage}

\begin{frame}{Method at a glance}
  \begin{columns}[T]
    \begin{column}{0.48\textwidth}
      \begin{block}{Representation}
        Gaussian infilling adds internal particles so the representation can support volume-aware simulation.
      \end{block}
      \begin{block}{Physics}
        Mixed-material CD-MPM transfers state between Gaussian particles and an Eulerian grid.
      \end{block}
    \end{column}
    \begin{column}{0.48\textwidth}
      \begin{alertblock}{Key question}
        Does the same representation remain renderable after deformation and fracture?
      \end{alertblock}
      \[
        L_{total}=L_{MSE}+L_{SSIM}+\lambda\sum_i\lVert s_i\rVert_2^2
      \]
    \end{column}
  \end{columns}
\end{frame}

\begin{frame}{Original paper Figure 1}
  \centering
  \includegraphics[width=0.90\linewidth]{figures/figure-1-teaser.png}
\end{frame}

\end{document}
'''

ARTIFACT_MARKER = "<!-- mary-slides:v1 -->"
CLASS_PATTERN = re.compile(r"<!--\s*_class:\s*([^>]+?)\s*-->", flags=re.IGNORECASE)
SECTION_PATTERN = re.compile(
    r"<!--\s*section:\s*(background|method|experiments|takeaways)\s*-->",
    flags=re.IGNORECASE,
)
CLAIMS_PATTERN = re.compile(r"<!--\s*claims:\s*([^>]+?)\s*-->", flags=re.IGNORECASE)
CLAIM_ID_PATTERN = re.compile(r"[BME][0-9]{2,}")
VISIBLE_CLAIM_PATTERN = re.compile(r"\[([BME][0-9]{2,})\]")
COMMENT_PATTERN = re.compile(r"<!--.*?-->", flags=re.DOTALL)
HTML_TAG_PATTERN = re.compile(r"<[^>]+>")
MARKDOWN_IMAGE_PATTERN = re.compile(r"!\[[^\]]*\]\(([^)]+)\)")
CSS_URL_PATTERN = re.compile(r"url\(\s*(['\"]?)(.*?)\1\s*\)", flags=re.IGNORECASE)
HTML_VOID_TAGS = {
    "area",
    "base",
    "br",
    "col",
    "embed",
    "hr",
    "img",
    "input",
    "link",
    "meta",
    "param",
    "source",
    "track",
    "wbr",
}
FIGURE_CAPTION_PATTERN = re.compile(
    r"(?:\bfig(?:ure)?\.?|图)\s*([0-9]+(?:[a-z])?)\s*[:.\-]?\s*([^\n]{0,220})",
    flags=re.IGNORECASE,
)
FIGURE_REFERENCE_PATTERN = re.compile(
    r"(?:\bfig(?:ure)?\.?|图)\s*([0-9]+(?:[a-z])?)",
    flags=re.IGNORECASE,
)

JsonObject = dict[str, Any]


class PaperSlidesError(ValueError):
    """A slides input, reference, layout, or artifact violated the P5 contract."""


def project_root_from_workspace(workspace: Path) -> Path:
    directory = Path(workspace).resolve()
    if directory.parent.name != "papers" or directory.parent.parent.name != ".mary-research":
        raise PaperSlidesError(
            "Paper workspace must be <project>/.mary-research/papers/<paper-id>."
        )
    return directory.parents[2]


def strip_jsonc(text: str) -> str:
    """Remove JSONC comments and trailing commas without touching string contents."""
    output: list[str] = []
    index = 0
    in_string = False
    escaped = False
    while index < len(text):
        character = text[index]
        following = text[index + 1] if index + 1 < len(text) else ""
        if in_string:
            output.append(character)
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
            index += 1
            continue
        if character == '"':
            in_string = True
            output.append(character)
            index += 1
            continue
        if character == "/" and following == "/":
            output.extend("  ")
            index += 2
            while index < len(text) and text[index] not in "\r\n":
                output.append(" ")
                index += 1
            continue
        if character == "/" and following == "*":
            output.extend("  ")
            index += 2
            while index < len(text):
                if index + 1 < len(text) and text[index : index + 2] == "*/":
                    output.extend("  ")
                    index += 2
                    break
                output.append("\n" if text[index] == "\n" else " ")
                index += 1
            else:
                raise PaperSlidesError(".vscode/settings.json contains an unclosed block comment.")
            continue
        output.append(character)
        index += 1

    uncommented = "".join(output)
    result: list[str] = []
    index = 0
    in_string = False
    escaped = False
    while index < len(uncommented):
        character = uncommented[index]
        if in_string:
            result.append(character)
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
            index += 1
            continue
        if character == '"':
            in_string = True
            result.append(character)
            index += 1
            continue
        if character == ",":
            lookahead = index + 1
            while lookahead < len(uncommented) and uncommented[lookahead].isspace():
                lookahead += 1
            if lookahead < len(uncommented) and uncommented[lookahead] in "]}":
                index += 1
                continue
        result.append(character)
        index += 1
    return "".join(result)


def load_vscode_settings(path: Path) -> JsonObject:
    if not path.is_file():
        return {}
    try:
        payload = json.loads(strip_jsonc(path.read_text(encoding="utf-8")))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise PaperSlidesError(f"Cannot merge invalid {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise PaperSlidesError(f"Cannot merge {path}: top-level value must be an object.")
    return payload


def required_vscode_settings(settings: JsonObject) -> JsonObject:
    merged = dict(settings)
    themes = merged.get("markdown.marp.themes", [])
    if not isinstance(themes, list) or any(not isinstance(value, str) for value in themes):
        raise PaperSlidesError(
            ".vscode/settings.json markdown.marp.themes must be an array of strings."
        )
    merged["markdown.marp.html"] = "all"
    merged["markdown.marp.mathTypesetting"] = "katex"
    merged["markdown.marp.themes"] = [
        *(value for value in themes if value != VSCODE_THEME_REFERENCE),
        VSCODE_THEME_REFERENCE,
    ]
    return merged


def install_project_marp_support(project_root: Path) -> JsonObject:
    """Install the offline theme and VS Code registration into a target project."""
    root = Path(project_root).resolve()
    if not THEME_PATH.is_file():
        raise PaperSlidesError(f"Localized Marp theme is missing: {THEME_PATH}")
    settings_path = root / VSCODE_SETTINGS_RELATIVE
    settings = load_vscode_settings(settings_path)
    merged = required_vscode_settings(settings)

    theme_target = root / PROJECT_THEME_RELATIVE
    theme_target.parent.mkdir(parents=True, exist_ok=True)
    source_fingerprint = sha256_file(THEME_PATH)
    if not theme_target.is_file() or sha256_file(theme_target) != source_fingerprint:
        atomic_write_text(theme_target, THEME_PATH.read_text(encoding="utf-8"))

    if settings != merged:
        settings_path.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text(
            settings_path,
            json.dumps(merged, ensure_ascii=False, indent=2) + "\n",
        )
    return {
        "theme_path": str(theme_target),
        "theme_reference": VSCODE_THEME_REFERENCE,
        "theme_fingerprint": source_fingerprint,
        "vscode_settings": str(settings_path),
    }


def install_paper_build_support(workspace: Path) -> JsonObject:
    """Install a reproducible Marp Makefile and isolated Hypo preview source."""
    directory = Path(workspace).resolve()
    project_root = project_root_from_workspace(directory)
    research_makefile = project_root / RESEARCH_MAKEFILE
    if research_makefile.is_file() and RESEARCH_MAKEFILE_MARKER not in research_makefile.read_text(encoding="utf-8"):
        raise PaperSlidesError(
            f"Existing {research_makefile} is not a Mary-generated research build file; "
            "move it aside before prepare-slides installs the managed target."
        )
    if not research_makefile.is_file() or research_makefile.read_text(encoding="utf-8") != RESEARCH_MAKEFILE_TEMPLATE:
        atomic_write_text(research_makefile, RESEARCH_MAKEFILE_TEMPLATE)

    makefile = directory / PAPER_MAKEFILE
    if makefile.is_file() and PAPER_MAKEFILE_MARKER not in makefile.read_text(encoding="utf-8"):
        raise PaperSlidesError(
            f"Existing {makefile} is not a Mary-generated paper build file; "
            "move it aside before prepare-slides installs the managed target."
        )
    if not makefile.is_file() or makefile.read_text(encoding="utf-8") != PAPER_MAKEFILE_TEMPLATE:
        atomic_write_text(makefile, PAPER_MAKEFILE_TEMPLATE)

    preview = directory / HYPO_PREVIEW_FILE
    preview.parent.mkdir(parents=True, exist_ok=True)
    if not preview.is_file() or preview.read_text(encoding="utf-8") != HYPO_PREVIEW_TEMPLATE:
        atomic_write_text(preview, HYPO_PREVIEW_TEMPLATE)
    return {
        "makefile": str(makefile),
        "makefile_marker": PAPER_MAKEFILE_MARKER,
        "research_makefile": str(research_makefile),
        "research_makefile_marker": RESEARCH_MAKEFILE_MARKER,
        "default_target": "slide",
        "hypo_preview_target": "hypo-template",
        "hypo_preview_source": str(preview),
    }


def validate_paper_build_support(workspace: Path) -> JsonObject:
    """Verify the generated paper-local build entrypoints without rewriting them."""
    directory = Path(workspace).resolve()
    project_root = project_root_from_workspace(directory)
    research_makefile = project_root / RESEARCH_MAKEFILE
    if not research_makefile.is_file() or RESEARCH_MAKEFILE_MARKER not in research_makefile.read_text(encoding="utf-8"):
        raise PaperSlidesError("Project .mary-research Makefile is missing or stale; run prepare-slides again.")
    makefile = directory / PAPER_MAKEFILE
    preview = directory / HYPO_PREVIEW_FILE
    if not makefile.is_file() or PAPER_MAKEFILE_MARKER not in makefile.read_text(encoding="utf-8"):
        raise PaperSlidesError("Paper Makefile is missing or stale; run prepare-slides again.")
    if not preview.is_file() or "Hypo-Slide" not in preview.read_text(encoding="utf-8"):
        raise PaperSlidesError("Hypo template preview source is missing or stale; run prepare-slides again.")
    return {
        "makefile": str(makefile),
        "makefile_marker": PAPER_MAKEFILE_MARKER,
        "research_makefile": str(research_makefile),
        "research_makefile_marker": RESEARCH_MAKEFILE_MARKER,
        "default_target": "slide",
        "hypo_preview_target": "hypo-template",
        "hypo_preview_source": str(preview),
    }


def validate_project_marp_support(workspace: Path) -> JsonObject:
    root = project_root_from_workspace(workspace)
    theme_target = root / PROJECT_THEME_RELATIVE
    if not theme_target.is_file():
        raise PaperSlidesError("Project-local Marp theme is missing; run prepare-slides again.")
    source_fingerprint = sha256_file(THEME_PATH)
    if sha256_file(theme_target) != source_fingerprint:
        raise PaperSlidesError("Project-local Marp theme is stale; run prepare-slides again.")
    settings_path = root / VSCODE_SETTINGS_RELATIVE
    settings = load_vscode_settings(settings_path)
    if required_vscode_settings(settings) != settings:
        raise PaperSlidesError(
            "Project VS Code Marp settings are missing or stale; run prepare-slides again."
        )
    return {
        "theme_path": str(theme_target),
        "theme_reference": VSCODE_THEME_REFERENCE,
        "theme_fingerprint": source_fingerprint,
        "vscode_settings": str(settings_path),
    }


def normalize_figure_id(token: str) -> str:
    return f"Figure {token.upper()}"


def extract_figure_catalog(blocks: dict[str, list[JsonObject]]) -> list[JsonObject]:
    catalog: dict[str, JsonObject] = {}
    for locator, spans in sorted(blocks.items()):
        for span in spans:
            content = str(span.get("content") or "")
            for match in FIGURE_CAPTION_PATTERN.finditer(content):
                figure_id = normalize_figure_id(match.group(1))
                caption = " ".join(match.group(0).split())[:280]
                item = catalog.setdefault(
                    figure_id,
                    {"figure_id": figure_id, "caption": caption, "source_locators": []},
                )
                if locator not in item["source_locators"]:
                    item["source_locators"].append(locator)
    return [catalog[key] for key in sorted(catalog, key=lambda value: (len(value), value))]


def build_slides_context(
    workspace: Path,
    *,
    paper_id: str,
    source_format: str,
    source_fingerprint: str,
    read_output_fingerprint: str,
    summary_output_fingerprint: str,
) -> JsonObject:
    directory = Path(workspace)
    try:
        summary_validation = validate_summary(
            directory,
            paper_id=paper_id,
            source_format=source_format,
            source_fingerprint=source_fingerprint,
            read_output_fingerprint=read_output_fingerprint,
        )
        ledger = load_summary_ledger(resolve_artifact_path(directory, SUMMARY_LEDGER_FILE))
    except PaperSummaryError as exc:
        raise PaperSlidesError(str(exc)) from exc
    if summary_validation["summary_bundle_fingerprint"] != summary_output_fingerprint:
        raise PaperSlidesError(
            "Current summary.md + summary-ledger.json bytes do not match the completed summary stage."
        )
    claim_catalog = [
        {
            "claim_id": claim["claim_id"],
            "section": {
                "B": "background",
                "M": "method",
                "E": "experiments",
            }[claim["claim_id"][0]],
            "claim_text": claim["claim_text"],
        }
        for claim in ledger["claims"]
    ]
    try:
        _, blocks, locator_fingerprint = validate_source_locator_index(
            directory,
            paper_id=paper_id,
            source_format=source_format,
            source_fingerprint=source_fingerprint,
        )
    except SourceLocatorError as exc:
        raise PaperSlidesError(str(exc)) from exc
    if not THEME_PATH.is_file():
        raise PaperSlidesError(f"Localized Marp theme is missing: {THEME_PATH}")

    build_support = validate_paper_build_support(directory)
    metadata = summary_validation["metadata"]
    return {
        "slides_context_schema": SLIDES_CONTEXT_SCHEMA,
        "paper_id": paper_id,
        "inputs": {
            "summary": {
                "artifact": SUMMARY_FILE,
                "fingerprint": metadata["summary_body_fingerprint"],
            },
            "summary_ledger": {
                "artifact": SUMMARY_LEDGER_FILE,
                "fingerprint": metadata["summary_ledger_fingerprint"],
            },
            "summary_bundle": {"fingerprint": summary_output_fingerprint},
            "source_locators": {
                "artifact": SOURCE_LOCATOR_FILE,
                "fingerprint": locator_fingerprint,
            },
        },
        "presentation": {
            "theme": THEME_NAME,
            "theme_fingerprint": sha256_file(THEME_PATH),
            "size": "16:9",
            "math": "katex",
            "figure_directory": FIGURES_DIR,
            "build": build_support,
            "lint_limits": {
                "max_pages": MAX_PAGES,
                "max_visible_characters_per_page": MAX_VISIBLE_CHARACTERS,
                "max_visible_lines_per_page": MAX_VISIBLE_LINES,
                "max_list_items_per_page": MAX_LIST_ITEMS,
                "max_code_lines_per_page": MAX_CODE_LINES,
            },
        },
        "claim_catalog": claim_catalog,
        "figure_catalog": extract_figure_catalog(blocks),
    }


def write_slides_context(
    workspace: Path,
    *,
    paper_id: str,
    source_format: str,
    source_fingerprint: str,
    read_output_fingerprint: str,
    summary_output_fingerprint: str,
) -> JsonObject:
    directory = Path(workspace)
    install_project_marp_support(project_root_from_workspace(directory))
    install_paper_build_support(directory)
    context = build_slides_context(
        directory,
        paper_id=paper_id,
        source_format=source_format,
        source_fingerprint=source_fingerprint,
        read_output_fingerprint=read_output_fingerprint,
        summary_output_fingerprint=summary_output_fingerprint,
    )
    atomic_write_text(
        artifact_path(directory, SLIDES_CONTEXT_FILE, create_parent=True),
        json.dumps(context, ensure_ascii=False, indent=2) + "\n",
    )
    (directory / FIGURES_DIR).mkdir(exist_ok=True)
    return context


def validate_slides_context(
    workspace: Path,
    *,
    paper_id: str,
    source_format: str,
    source_fingerprint: str,
    read_output_fingerprint: str,
    summary_output_fingerprint: str,
) -> tuple[JsonObject, str]:
    context_path = resolve_artifact_path(workspace, SLIDES_CONTEXT_FILE)
    if not context_path.is_file():
        raise PaperSlidesError(f"{SLIDES_CONTEXT_FILE} is missing; run prepare-slides first.")
    try:
        stored = json.loads(context_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise PaperSlidesError(f"{SLIDES_CONTEXT_FILE} is invalid: {exc}") from exc
    validate_project_marp_support(workspace)
    expected = build_slides_context(
        workspace,
        paper_id=paper_id,
        source_format=source_format,
        source_fingerprint=source_fingerprint,
        read_output_fingerprint=read_output_fingerprint,
        summary_output_fingerprint=summary_output_fingerprint,
    )
    if stored != expected:
        raise PaperSlidesError(f"{SLIDES_CONTEXT_FILE} is stale or does not match current inputs.")
    return stored, sha256_file(context_path)


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise PaperSlidesError("slides.md must begin with YAML frontmatter.")
    try:
        end = next(index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---")
    except StopIteration as exc:
        raise PaperSlidesError("slides.md frontmatter is not closed by ---.") from exc
    frontmatter: dict[str, str] = {}
    for line in lines[1:end]:
        if not line.strip():
            continue
        if ":" not in line:
            raise PaperSlidesError(f"slides.md frontmatter line is not key: value: {line}")
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if not key or key in frontmatter:
            raise PaperSlidesError(f"slides.md frontmatter has an empty or duplicate key: {key}")
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        frontmatter[key] = value
    for key, expected in REQUIRED_FRONTMATTER.items():
        if frontmatter.get(key, "").casefold() != expected.casefold():
            raise PaperSlidesError(f"slides.md frontmatter requires {key}: {expected}.")
    return frontmatter, "\n".join(lines[end + 1 :]).strip()


def page_classes(page: str) -> set[str]:
    classes: set[str] = set()
    for declaration in CLASS_PATTERN.findall(page):
        classes.update(declaration.split())
    return classes


def page_claims(page: str, page_number: int) -> list[str]:
    declarations = CLAIMS_PATTERN.findall(page)
    if len(declarations) != 1:
        raise PaperSlidesError(
            f"slides.md page {page_number} must contain exactly one <!-- claims: ... --> declaration."
        )
    tokens = [token for token in re.split(r"[\s,]+", declarations[0].strip()) if token]
    if not tokens or any(CLAIM_ID_PATTERN.fullmatch(token) is None for token in tokens):
        raise PaperSlidesError(f"slides.md page {page_number} has an invalid claims declaration.")
    if len(set(tokens)) != len(tokens):
        raise PaperSlidesError(f"slides.md page {page_number} has duplicate claim references.")
    return tokens


class SlideHTMLInspector(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.placeholders: list[JsonObject] = []
        self.image_sources: list[str] = []
        self._active: JsonObject | None = None
        self._stack: list[str] = []
        self._caption_depth: int | None = None

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self._handle_start(tag, attrs, self_closing=tag.casefold() in HTML_VOID_TAGS)

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self._handle_start(tag, attrs, self_closing=True)

    def _handle_start(
        self,
        tag: str,
        attrs: list[tuple[str, str | None]],
        *,
        self_closing: bool,
    ) -> None:
        attributes = {name: value or "" for name, value in attrs}
        classes = set(attributes.get("class", "").split())
        normalized_tag = tag.casefold()
        if normalized_tag == "img":
            self.image_sources.append(attributes.get("src", ""))
        if self._active is not None:
            if not self_closing:
                self._stack.append(normalized_tag)
            if "figure-placeholder__number" in classes:
                self._active["has_number_node"] = True
            if "figure-placeholder__caption" in classes:
                self._active["has_caption_node"] = True
                self._caption_depth = len(self._stack)
            return
        if normalized_tag == "div" and "figure-placeholder" in classes:
            self._active = {
                "figure_id": attributes.get("data-figure", ""),
                "source_locator": attributes.get("data-source-locator", ""),
                "classes": sorted(classes),
                "has_number_node": False,
                "has_caption_node": False,
                "text": [],
                "caption_text": [],
            }
            self._stack = [normalized_tag]
            self._caption_depth = None

    def handle_endtag(self, tag: str) -> None:
        if self._active is None:
            return
        normalized_tag = tag.casefold()
        if normalized_tag in HTML_VOID_TAGS:
            return
        if not self._stack:
            raise PaperSlidesError("slides.md contains an unexpected HTML closing tag.")
        if self._stack[-1] != normalized_tag:
            raise PaperSlidesError(
                f"slides.md contains mismatched HTML tags: expected </{self._stack[-1]}> but found </{normalized_tag}>."
            )
        self._stack.pop()
        if self._caption_depth is not None and len(self._stack) < self._caption_depth:
            self._caption_depth = None
        if not self._stack:
            self._active["text"] = " ".join(" ".join(self._active["text"]).split())
            self._active["caption_text"] = " ".join(
                " ".join(self._active["caption_text"]).split()
            )
            self.placeholders.append(self._active)
            self._active = None

    def handle_data(self, data: str) -> None:
        if self._active is not None:
            self._active["text"].append(data)
            if self._caption_depth is not None and len(self._stack) >= self._caption_depth:
                self._active["caption_text"].append(data)

    def close(self) -> None:
        super().close()
        if self._active is not None:
            raise PaperSlidesError(
                "slides.md contains an unclosed HTML element or figure-placeholder div."
            )


def validate_media_reference(workspace: Path, reference: str, page_number: int) -> None:
    value = reference.strip().strip("<>")
    if not value:
        raise PaperSlidesError(f"slides.md page {page_number} contains an empty image reference.")
    if re.match(r"^(?:https?:)?//", value, flags=re.IGNORECASE) or value.startswith("data:"):
        raise PaperSlidesError(
            f"slides.md page {page_number} image references must be local repository files: {value[:80]}"
        )
    path = PurePosixPath(value.replace("\\", "/"))
    if path.is_absolute() or ".." in path.parts:
        raise PaperSlidesError(f"slides.md page {page_number} has an unsafe image reference: {value}")
    target = (Path(workspace) / path.as_posix()).resolve()
    try:
        target.relative_to(Path(workspace).resolve())
    except ValueError as exc:
        raise PaperSlidesError(f"slides.md page {page_number} image escapes the paper workspace: {value}") from exc
    if not target.is_file():
        raise PaperSlidesError(f"slides.md page {page_number} image does not exist: {value}")


def visible_page_metrics(page: str) -> JsonObject:
    without_comments = COMMENT_PATTERN.sub("", page)
    without_tags = HTML_TAG_PATTERN.sub(" ", without_comments)
    visible = unescape(without_tags)
    compact = re.sub(r"\s+", "", visible)
    visible_lines = [line for line in visible.splitlines() if line.strip()]
    list_items = len(re.findall(r"(?m)^\s*(?:[-*+]|\d+[.)])\s+", visible))
    code_lines = 0
    in_code = False
    for line in visible.splitlines():
        if line.strip().startswith("```"):
            in_code = not in_code
        elif in_code and line.strip():
            code_lines += 1
    return {
        "visible_characters": len(compact),
        "visible_lines": len(visible_lines),
        "list_items": list_items,
        "code_lines": code_lines,
    }


def validate_page_capacity(page: str, page_number: int) -> JsonObject:
    metrics = visible_page_metrics(page)
    limits = {
        "visible_characters": MAX_VISIBLE_CHARACTERS,
        "visible_lines": MAX_VISIBLE_LINES,
        "list_items": MAX_LIST_ITEMS,
        "code_lines": MAX_CODE_LINES,
    }
    for field, limit in limits.items():
        if metrics[field] > limit:
            raise PaperSlidesError(
                f"slides.md page {page_number} exceeds {field} limit: {metrics[field]} > {limit}."
            )
    return metrics


def validate_slides_document(workspace: Path, text: str, context: JsonObject) -> JsonObject:
    _, body = parse_frontmatter(text)
    if body.count(ARTIFACT_MARKER) != 1:
        raise PaperSlidesError(f"slides.md must contain exactly one {ARTIFACT_MARKER} marker.")
    pages = [page.strip() for page in re.split(r"(?m)^---[ \t]*$", body)]
    if any(not page for page in pages):
        raise PaperSlidesError("slides.md contains an empty slide.")
    if len(pages) < 6 or len(pages) > MAX_PAGES:
        raise PaperSlidesError(f"slides.md must contain 6-{MAX_PAGES} slides; found {len(pages)}.")

    claim_sections = {item["claim_id"]: item["section"] for item in context["claim_catalog"]}
    figure_catalog = {item["figure_id"]: item for item in context["figure_catalog"]}
    section_counts = {section: 0 for section in SECTION_ORDER}
    section_sequence: list[str] = []
    referenced_claims: set[str] = set()
    referenced_figures: set[str] = set()
    layout_pages = 0
    placeholder_count = 0
    page_metrics: list[JsonObject] = []

    for index, page in enumerate(pages):
        page_number = index + 1
        classes = page_classes(page)
        headings_h1 = re.findall(r"(?m)^#[ \t]+\S.*$", page)
        headings_h2 = re.findall(r"(?m)^##[ \t]+\S.*$", page)
        if index == 0:
            if "cover_e" not in classes or len(headings_h1) != 1:
                raise PaperSlidesError("slides.md first slide must be a cover_e page with exactly one H1 title.")
            if SECTION_PATTERN.search(page) or CLAIMS_PATTERN.search(page):
                raise PaperSlidesError("slides.md cover page must not declare a content section or claims.")
        elif index == len(pages) - 1:
            closing_titles = re.findall(r"(?m)^######[ \t]+\S.*$", page)
            if "lastpage" not in classes or len(closing_titles) != 1:
                raise PaperSlidesError(
                    "slides.md last slide must use lastpage with exactly one non-empty H6 closing title."
                )
            if SECTION_PATTERN.search(page) or CLAIMS_PATTERN.search(page):
                raise PaperSlidesError("slides.md last page must not declare a content section or claims.")
            closing_body = re.sub(r"(?m)^######[ \t]+\S.*$", "", page, count=1)
            closing_body = COMMENT_PATTERN.sub("", closing_body)
            if HTML_TAG_PATTERN.search(closing_body):
                raise PaperSlidesError("slides.md last slide may contain only its H6 closing title.")
            closing_body = HTML_TAG_PATTERN.sub("", closing_body)
            if re.sub(r"\s+", "", unescape(closing_body)):
                raise PaperSlidesError("slides.md last slide may contain only its H6 closing title.")
        else:
            section_matches = [value.casefold() for value in SECTION_PATTERN.findall(page)]
            is_structural = bool(classes & STRUCTURAL_CLASSES)
            if is_structural and not section_matches:
                if CLAIMS_PATTERN.search(page):
                    raise PaperSlidesError(
                        f"slides.md structural page {page_number} must not declare claims without a section."
                    )
            else:
                if len(section_matches) != 1:
                    raise PaperSlidesError(
                        f"slides.md content page {page_number} requires exactly one section declaration."
                    )
                section = section_matches[0]
                section_counts[section] += 1
                section_sequence.append(section)
                if len(headings_h2) != 1:
                    raise PaperSlidesError(
                        f"slides.md content page {page_number} must contain exactly one H2 title."
                    )
                claims = page_claims(page, page_number)
                for claim_id in claims:
                    if claim_id not in claim_sections:
                        raise PaperSlidesError(
                            f"slides.md page {page_number} references unknown summary claim {claim_id}."
                        )
                    expected_prefix = SECTION_PREFIXES.get(section)
                    if expected_prefix and not claim_id.startswith(expected_prefix):
                        raise PaperSlidesError(
                            f"slides.md page {page_number} section {section} cannot cite {claim_id}."
                        )
                    referenced_claims.add(claim_id)
        if VISIBLE_CLAIM_PATTERN.search(COMMENT_PATTERN.sub("", page)):
            raise PaperSlidesError(
                f"slides.md page {page_number} exposes summary claim ids; keep them in <!-- claims: ... -->."
            )

        if classes & LAYOUT_CLASSES:
            layout_pages += 1
        inspector = SlideHTMLInspector()
        inspector.feed(page)
        inspector.close()
        page_placeholder_ids: set[str] = set()
        for placeholder in inspector.placeholders:
            figure_id = placeholder["figure_id"]
            if figure_id not in figure_catalog:
                raise PaperSlidesError(
                    f"slides.md page {page_number} placeholder references unknown {figure_id or 'figure'}."
                )
            if placeholder["source_locator"] not in figure_catalog[figure_id]["source_locators"]:
                raise PaperSlidesError(
                    f"slides.md page {page_number} placeholder locator does not resolve for {figure_id}."
                )
            if not set(placeholder["classes"]) & IMAGE_PANEL_CLASSES:
                raise PaperSlidesError(
                    f"slides.md page {page_number} figure-placeholder must use an image panel class."
                )
            if not placeholder["has_number_node"] or not placeholder["has_caption_node"]:
                raise PaperSlidesError(
                    f"slides.md page {page_number} placeholder requires number and caption nodes."
                )
            if figure_id not in placeholder["text"]:
                raise PaperSlidesError(
                    f"slides.md page {page_number} placeholder must visibly display {figure_id}."
                )
            expected_caption = " ".join(str(figure_catalog[figure_id]["caption"]).split())
            if placeholder["caption_text"] != expected_caption:
                raise PaperSlidesError(
                    f"slides.md page {page_number} caption does not exactly match {figure_id} context."
                )
            page_placeholder_ids.add(figure_id)
            referenced_figures.add(figure_id)
            placeholder_count += 1

        page_figure_ids = {
            normalize_figure_id(token) for token in FIGURE_REFERENCE_PATTERN.findall(page)
        }
        unknown_figures = sorted(page_figure_ids - set(figure_catalog))
        if unknown_figures:
            raise PaperSlidesError(
                f"slides.md page {page_number} references unknown figures: {', '.join(unknown_figures)}."
            )
        missing_placeholders = sorted(page_figure_ids - page_placeholder_ids)
        if missing_placeholders:
            raise PaperSlidesError(
                f"slides.md page {page_number} references figures without placeholders: "
                + ", ".join(missing_placeholders)
                + "."
            )

        media_references = [match.group(1).split()[0] for match in MARKDOWN_IMAGE_PATTERN.finditer(page)]
        media_references.extend(match.group(2).strip() for match in CSS_URL_PATTERN.finditer(page))
        media_references.extend(inspector.image_sources)
        for reference in media_references:
            validate_media_reference(workspace, reference, page_number)
        page_metrics.append({"page": page_number, **validate_page_capacity(page, page_number)})

    ranks = [SECTION_ORDER.index(section) for section in section_sequence]
    if ranks != sorted(ranks):
        raise PaperSlidesError("slides.md sections must progress background -> method -> experiments -> takeaways.")
    for required, minimum in (("background", 1), ("method", 2), ("experiments", 1)):
        if section_counts[required] < minimum:
            raise PaperSlidesError(
                f"slides.md requires at least {minimum} {required} content page(s)."
            )
    if section_counts["method"] < max(section_counts["background"], section_counts["experiments"]):
        raise PaperSlidesError("slides.md must keep Method at least as detailed as Background and Experiments.")
    if layout_pages < 2:
        raise PaperSlidesError("slides.md must use VSP-Marp multi-panel layouts on at least two pages.")
    if figure_catalog and placeholder_count == 0:
        raise PaperSlidesError("slides.md must include at least one placeholder from the Figure catalog.")
    missing_claim_families = [
        prefix for prefix in ("B", "M", "E") if not any(claim.startswith(prefix) for claim in referenced_claims)
    ]
    if missing_claim_families:
        raise PaperSlidesError(
            "slides.md must cite background, method, and experiment claim families; missing: "
            + ", ".join(missing_claim_families)
            + "."
        )

    return {
        "page_count": len(pages),
        "section_page_counts": section_counts,
        "layout_page_count": layout_pages,
        "claim_reference_count": len(referenced_claims),
        "referenced_claim_ids": sorted(referenced_claims),
        "figure_placeholder_count": placeholder_count,
        "referenced_figure_ids": sorted(referenced_figures),
        "page_metrics": page_metrics,
    }


def validate_slides(
    workspace: Path,
    *,
    paper_id: str,
    source_format: str,
    source_fingerprint: str,
    read_output_fingerprint: str,
    summary_output_fingerprint: str,
) -> JsonObject:
    directory = Path(workspace)
    slides_path = directory / SLIDES_FILE
    if not slides_path.is_file():
        raise PaperSlidesError(f"{SLIDES_FILE} is missing.")
    context, context_fingerprint = validate_slides_context(
        directory,
        paper_id=paper_id,
        source_format=source_format,
        source_fingerprint=source_fingerprint,
        read_output_fingerprint=read_output_fingerprint,
        summary_output_fingerprint=summary_output_fingerprint,
    )
    report = validate_slides_document(
        directory,
        slides_path.read_text(encoding="utf-8"),
        context,
    )
    return {
        "slides_fingerprint": sha256_file(slides_path),
        "metadata": {
            "slides_context_schema": SLIDES_CONTEXT_SCHEMA,
            "slides_context": SLIDES_CONTEXT_FILE,
            "slides_context_fingerprint": context_fingerprint,
            "theme": THEME_NAME,
            "theme_fingerprint": context["presentation"]["theme_fingerprint"],
            "math": "katex",
            "size": "16:9",
            **report,
        },
    }


def run_marp_smoke(workspace: Path) -> JsonObject:
    directory = Path(workspace)
    slides_path = directory / SLIDES_FILE
    marp = shutil.which("marp")
    if marp:
        command = [marp]
    else:
        npx = shutil.which("npx")
        if npx is None:
            raise PaperSlidesError("Marp smoke compile requires marp or npx on PATH.")
        command = [npx, "--offline", "--yes", "@marp-team/marp-cli@4.3.1"]
    with tempfile.TemporaryDirectory(prefix="mary-marp-smoke-") as temporary:
        output = Path(temporary) / "slides.html"
        completed = subprocess.run(
            [
                *command,
                "--config-file",
                str(MARP_CONFIG_PATH),
                str(slides_path),
                "--output",
                str(output),
            ],
            cwd=directory,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=90,
            check=False,
        )
        if completed.returncode != 0 or not output.is_file():
            detail = " ".join((completed.stderr or completed.stdout).split())[-500:]
            raise PaperSlidesError(f"Optional Marp smoke compile failed: {detail or 'no output'}")
    return {"status": "passed", "runner": Path(command[0]).name}
