#!/usr/bin/env python3
"""Grounded VSP-Beamer slide artifacts, compilation, and PDF auditing."""

from __future__ import annotations

import json
from pathlib import Path, PurePosixPath
import re
import shutil
import subprocess
from typing import Any

from mw_paper_artifacts import (
    PARSE_QUALITY_FILE,
    SLIDES_CONTEXT_FILE,
    SOURCE_LOCATOR_FILE,
    artifact_path,
    resolve_artifact_path,
)
from mw_paper_locators import SourceLocatorError, validate_source_locator_index
from mw_paper_sources import sha256_file
from mw_paper_summary import (
    PaperSummaryError,
    SUMMARY_FILE,
    SUMMARY_LEDGER_FILE,
    load_summary_ledger,
    validate_summary,
)
from mw_runtime import atomic_write_text
from validate_beamer_assets import (
    ASSET_ROOT as BEAMER_ASSET_ROOT,
    RUNTIME_FILES as BEAMER_RUNTIME_FILES,
    bundle_fingerprint as beamer_bundle_fingerprint,
    validate_beamer_assets,
)


SLIDES_CONTEXT_SCHEMA = 2
SLIDES_FILE = "slides.tex"
FIGURES_DIR = "figures"
PAPER_MAKEFILE = "Makefile"
HYPO_PREVIEW_DIR = "hypo-template-preview"
HYPO_PREVIEW_FILE = f"{HYPO_PREVIEW_DIR}/Slide.tex"
PAPER_MAKEFILE_MARKER = "# mary-paper-beamer-build:v2"
LEGACY_PAPER_MAKEFILE_MARKER = "# mary-paper-build:v1"
RESEARCH_MAKEFILE = Path(".mary-research") / "Makefile"
RESEARCH_MAKEFILE_MARKER = "# mary-research-beamer-build:v2"
LEGACY_RESEARCH_MAKEFILE_MARKER = "# mary-research-build:v1"
THEME_NAME = "mary-shanghaitech-red"
PLUGIN_ROOT = Path(__file__).resolve().parents[1]
THEME_PATH = BEAMER_ASSET_ROOT / "themes" / f"beamertheme{THEME_NAME}.sty"
BEAMER_AUDIT_SCRIPT_PATH = PLUGIN_ROOT / "scripts" / "mw_beamer_audit.sh"
PROJECT_BEAMER_RELATIVE = Path(".mary-research") / "beamer"
PROJECT_THEME_RELATIVE = PROJECT_BEAMER_RELATIVE / "themes" / THEME_PATH.name
PROJECT_PDF_RELATIVE = Path("build") / "slides.pdf"
PROJECT_LOG_RELATIVE = Path(".beamer-cache") / "slides.log"

REQUIRED_PREAMBLE = {
    "documentclass": r"\documentclass[aspectratio=169,10pt]{beamer}",
    "ctex": r"\usepackage[UTF8,fontset=none]{ctex}",
    "theme": rf"\usetheme{{{THEME_NAME}}}",
}
SECTION_ORDER = ("background", "method", "experiments", "takeaways")
SECTION_PREFIXES = {"background": "B", "method": "M", "experiments": "E"}
LAYOUT_CLASSES = {
    "cols-2",
    "cols-2-73",
    "cols-2-64",
    "cols-2-37",
    "cols-2-46",
    "cols-3",
    "rows-2",
    "rows-2-73",
    "rows-2-64",
    "rows-2-55",
    "rows-2-37",
    "rows-2-28",
    "pin-3",
}
IMAGE_PANEL_CLASSES = {"limg", "mimg", "rimg", "timg", "bimg"}
STRUCTURAL_CLASSES = {"trans", "toc_a", "toc_b"}
MAX_PAGES = 24
MAX_VISIBLE_CHARACTERS = 900
MAX_VISIBLE_LINES = 36
MAX_LIST_ITEMS = 8
MAX_CODE_LINES = 14
RASTER_IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"}
LATEX_FIGURE_PATTERN = re.compile(
    r"\\begin\{(?:figure|figure\*)\}.*?\\end\{(?:figure|figure\*)\}", re.DOTALL
)
LATEX_GRAPHICS_PATTERN = re.compile(r"\\includegraphics(?:\[[^]]*\])?\s*\{([^{}]+)\}")
LATEX_CAPTIONOF_FIGURE_PATTERN = re.compile(
    r"\\captionof\s*\{\s*figure\s*\}\s*\{", re.IGNORECASE
)

PAPER_MAKEFILE_TEMPLATE = r'''# mary-paper-beamer-build:v2
# Generated by Mary Workflow. The existing slides.tex is never rewritten by these targets.

PROJECT_ROOT := $(abspath $(CURDIR)/../../..)
SLIDES := slides.tex
BUILD_DIR ?= build
BEAMER_ROOT := $(PROJECT_ROOT)/.mary-research/beamer
THEME_ROOT := $(BEAMER_ROOT)/themes
ASSET_ROOT := $(BEAMER_ROOT)/assets
THEME_FILES := $(wildcard $(THEME_ROOT)/*.sty)
LATEXMK ?= latexmk
LATEXMK_FLAGS := -xelatex -interaction=nonstopmode -halt-on-error -file-line-error
TEXINPUTS_ENV := $(THEME_ROOT)//:$(ASSET_ROOT)//:$(CURDIR)//:
MW_PAPER_SCRIPT ?= $(HOME)/.codex/skills/mary-workflow/scripts/mw_paper.py
PAPER_ID ?= $(notdir $(CURDIR))
HYPO_PATH ?= $(PROJECT_ROOT)/../Hypoxanthine-LaTeX
HYPO_PREVIEW := hypo-template-preview/Slide.tex

.PHONY: slide slides audit-slides audit hypo-template clean

slide slides: $(BUILD_DIR)/slides.pdf

$(BUILD_DIR)/slides.pdf: $(SLIDES) $(THEME_FILES)
	@mkdir -p "$(BUILD_DIR)" ".beamer-cache"
	TEXINPUTS="$(TEXINPUTS_ENV)" $(LATEXMK) $(LATEXMK_FLAGS) -outdir=".beamer-cache" "$(SLIDES)"
	@! grep -En 'Overfull|Missing character|LaTeX Error|LaTeX Font Warning|Package .* Warning' ".beamer-cache/slides.log"
	cp ".beamer-cache/slides.pdf" "$@"

audit-slides audit:
	@test -f "$(MW_PAPER_SCRIPT)" || (echo "Set MW_PAPER_SCRIPT to the Mary Workflow runtime."; exit 2)
	python3 "$(MW_PAPER_SCRIPT)" --project-root "$(PROJECT_ROOT)" lint-slides --paper-id "$(PAPER_ID)" --audit-pdf

# Compile a separate, original Hypoxanthine-LaTeX preview for visual comparison.
# This target never changes slides.tex or build/slides.pdf.
hypo-template: $(BUILD_DIR)/hypo-template-preview.pdf

$(BUILD_DIR)/hypo-template-preview.pdf: $(HYPO_PREVIEW)
	@test -f "$(HYPO_PATH)/make/Hypoxanthine.mk" || (echo "Set HYPO_PATH to the Hypoxanthine-LaTeX checkout."; exit 2)
	$(MAKE) -f "$(HYPO_PATH)/make/Hypoxanthine.mk" HYPO_PATH="$(HYPO_PATH)" NAME=hypo-template-preview MAIN_FILE="$(CURDIR)/$(HYPO_PREVIEW)" OUT_DIR="$(CURDIR)/$(BUILD_DIR)/hypo-template-preview" SHELL_ESCAPE=1 all
	cp "$(BUILD_DIR)/hypo-template-preview/Slide.pdf" "$@"

clean:
	rm -rf "$(BUILD_DIR)" ".beamer-cache"
'''

RESEARCH_MAKEFILE_TEMPLATE = r'''# mary-research-beamer-build:v2
# Generated by Mary Workflow. This dispatcher never rewrites any paper artifact.

RESEARCH_ROOT := $(abspath $(CURDIR))
PROJECT_ROOT := $(abspath $(RESEARCH_ROOT)/..)
PAPER_DIRS := $(wildcard $(RESEARCH_ROOT)/papers/*)
PAPER_IDS := $(notdir $(PAPER_DIRS))
PAPER_ID ?= $(firstword $(PAPER_IDS))
PAPER_DIR := $(RESEARCH_ROOT)/papers/$(PAPER_ID)
MW_PAPER_SCRIPT ?= $(HOME)/.codex/skills/mary-workflow/scripts/mw_paper.py

.PHONY: slide slides audit-slides audit hypo-template clean check

slide: check
	$(MAKE) -C "$(PAPER_DIR)" slide

slides: slide

audit-slides audit: check
	@test -f "$(MW_PAPER_SCRIPT)" || (echo "Set MW_PAPER_SCRIPT to the Mary Workflow runtime."; exit 2)
	python3 "$(MW_PAPER_SCRIPT)" --project-root "$(PROJECT_ROOT)" lint-slides --paper-id "$(PAPER_ID)" --audit-pdf

hypo-template: check
	$(MAKE) -C "$(PAPER_DIR)" hypo-template

clean: check
	$(MAKE) -C "$(PAPER_DIR)" clean

check:
	@test -n "$(PAPER_ID)" || (echo "No paper workspace found under $(RESEARCH_ROOT)/papers."; exit 2)
	@test -d "$(PAPER_DIR)" || (echo "Unknown PAPER_ID=$(PAPER_ID); use make PAPER_ID=<paper-id> slide."; exit 2)
'''

HYPO_PREVIEW_TEMPLATE = r'''\documentclass[theme=school, aspectratio=169]{Hypo-Slide}

\HypoSlideSetup{
  title={GaussianFluent},
  subtitle={Original Hypoxanthine-LaTeX template preview},
  author={Bei Huang et al.},
  institute={ShanghaiTech University},
  date={2026}
}

\begin{document}

\frame{\titlepage}

\begin{frame}{Method at a glance}
  \begin{columns}[T]
    \begin{column}{0.48\textwidth}
      \begin{block}{Representation}
        Gaussian infilling adds internal particles so the representation can support volume-aware simulation.
      \end{block}
      \begin{block}{Physics}
        Mixed-material CD-MPM transfers state between Gaussian particles and an Eulerian grid.
      \end{block}
    \end{column}
    \begin{column}{0.48\textwidth}
      \begin{alertblock}{Key question}
        Does the same representation remain renderable after deformation and fracture?
      \end{alertblock}
      \[
        L_{total}=L_{MSE}+L_{SSIM}+\lambda\sum_i\lVert s_i\rVert_2^2
      \]
    \end{column}
  \end{columns}
\end{frame}

\begin{frame}{Original paper Figure 1}
  \centering
  \includegraphics[width=0.90\linewidth]{figures/figure-1-teaser.png}
\end{frame}

\end{document}
'''

ARTIFACT_MARKER = "% mary-slides:v2"
SECTION_PATTERN = re.compile(
    r"(?m)^\s*%\s*mary-section:\s*(background|method|experiments|takeaways)\s*$",
    flags=re.IGNORECASE,
)
CLAIMS_PATTERN = re.compile(r"(?m)^\s*%\s*mary-claims:\s*([^\r\n%]+?)\s*$", re.IGNORECASE)
CLAIM_ID_PATTERN = re.compile(r"[BME][0-9]{2,}")
VISIBLE_CLAIM_PATTERN = re.compile(r"\[([BME][0-9]{2,})\]")
TEX_COMMENT_PATTERN = re.compile(r"(?m)(?<!\\)%.*$")
FRAME_PATTERN = re.compile(
    r"\\begin\{frame\}(?:\[[^]]*\])?(?:\{([^{}]*)\})?(.*?)\\end\{frame\}",
    flags=re.DOTALL,
)
FIGURE_METADATA_PATTERN = re.compile(r"(?m)^\s*%\s*mary-figure:\s*(\{.*\})\s*$")
FIGURE_CAPTION_PATTERN = re.compile(
    r"(?:\bfig(?:ure)?\.?|图)\s*([0-9]+(?:[a-z])?)\s*[:.\-]?\s*([^\n]{0,220})",
    flags=re.IGNORECASE,
)
FIGURE_REFERENCE_PATTERN = re.compile(
    r"(?:\bfig(?:ure)?\.?|图)\s*([0-9]+(?:[a-z])?)",
    flags=re.IGNORECASE,
)
LATEX_COMMAND_PATTERN = re.compile(r"\\[A-Za-z@]+\*?(?:\[[^]]*\])?")

JsonObject = dict[str, Any]


class PaperSlidesError(ValueError):
    """A slides input, reference, layout, or artifact violated the P5 contract."""


def project_root_from_workspace(workspace: Path) -> Path:
    directory = Path(workspace).resolve()
    if directory.parent.name != "papers" or directory.parent.parent.name != ".mary-research":
        raise PaperSlidesError(
            "Paper workspace must be <project>/.mary-research/papers/<paper-id>."
        )
    return directory.parents[2]


def install_project_beamer_support(project_root: Path) -> JsonObject:
    """Install the pinned offline VSP-Beamer bundle into a target project."""
    root = Path(project_root).resolve()
    try:
        report = validate_beamer_assets()
    except ValueError as exc:
        raise PaperSlidesError(str(exc)) from exc
    installed: list[str] = []
    for source in BEAMER_RUNTIME_FILES:
        relative = source.relative_to(BEAMER_ASSET_ROOT)
        target = root / PROJECT_BEAMER_RELATIVE / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.is_file() and sha256_file(target) == sha256_file(source):
            installed.append(target.relative_to(root).as_posix())
            continue
        if source.suffix == ".sty":
            atomic_write_text(target, source.read_text(encoding="utf-8"))
        else:
            shutil.copyfile(source, target)
        installed.append(target.relative_to(root).as_posix())
    return {
        "runtime_root": str(root / PROJECT_BEAMER_RELATIVE),
        "theme_path": str(root / PROJECT_THEME_RELATIVE),
        "bundle_fingerprint": report["bundle_fingerprint"],
        "runtime_files": installed,
    }


def install_paper_build_support(workspace: Path) -> JsonObject:
    """Install a reproducible Beamer Makefile and isolated Hypo preview source."""
    directory = Path(workspace).resolve()
    project_root = project_root_from_workspace(directory)
    research_makefile = project_root / RESEARCH_MAKEFILE
    if research_makefile.is_file() and not any(
        marker in research_makefile.read_text(encoding="utf-8")
        for marker in (RESEARCH_MAKEFILE_MARKER, LEGACY_RESEARCH_MAKEFILE_MARKER)
    ):
        raise PaperSlidesError(
            f"Existing {research_makefile} is not a Mary-generated research build file; "
            "move it aside before prepare-slides installs the managed target."
        )
    if not research_makefile.is_file() or research_makefile.read_text(encoding="utf-8") != RESEARCH_MAKEFILE_TEMPLATE:
        atomic_write_text(research_makefile, RESEARCH_MAKEFILE_TEMPLATE)

    makefile = directory / PAPER_MAKEFILE
    if makefile.is_file() and not any(
        marker in makefile.read_text(encoding="utf-8")
        for marker in (PAPER_MAKEFILE_MARKER, LEGACY_PAPER_MAKEFILE_MARKER)
    ):
        raise PaperSlidesError(
            f"Existing {makefile} is not a Mary-generated paper build file; "
            "move it aside before prepare-slides installs the managed target."
        )
    if not makefile.is_file() or makefile.read_text(encoding="utf-8") != PAPER_MAKEFILE_TEMPLATE:
        atomic_write_text(makefile, PAPER_MAKEFILE_TEMPLATE)

    preview = directory / HYPO_PREVIEW_FILE
    preview.parent.mkdir(parents=True, exist_ok=True)
    if not preview.is_file() or preview.read_text(encoding="utf-8") != HYPO_PREVIEW_TEMPLATE:
        atomic_write_text(preview, HYPO_PREVIEW_TEMPLATE)
    return {
        "makefile": str(makefile),
        "makefile_marker": PAPER_MAKEFILE_MARKER,
        "research_makefile": str(research_makefile),
        "research_makefile_marker": RESEARCH_MAKEFILE_MARKER,
        "default_target": "slide",
        "hypo_preview_target": "hypo-template",
        "hypo_preview_source": str(preview),
    }


def validate_paper_build_support(workspace: Path) -> JsonObject:
    """Verify the generated paper-local build entrypoints without rewriting them."""
    directory = Path(workspace).resolve()
    project_root = project_root_from_workspace(directory)
    research_makefile = project_root / RESEARCH_MAKEFILE
    if not research_makefile.is_file() or RESEARCH_MAKEFILE_MARKER not in research_makefile.read_text(encoding="utf-8"):
        raise PaperSlidesError("Project .mary-research Makefile is missing or stale; run prepare-slides again.")
    makefile = directory / PAPER_MAKEFILE
    preview = directory / HYPO_PREVIEW_FILE
    if not makefile.is_file() or PAPER_MAKEFILE_MARKER not in makefile.read_text(encoding="utf-8"):
        raise PaperSlidesError("Paper Makefile is missing or stale; run prepare-slides again.")
    if not preview.is_file() or "Hypo-Slide" not in preview.read_text(encoding="utf-8"):
        raise PaperSlidesError("Hypo template preview source is missing or stale; run prepare-slides again.")
    return {
        "makefile": str(makefile),
        "makefile_marker": PAPER_MAKEFILE_MARKER,
        "research_makefile": str(research_makefile),
        "research_makefile_marker": RESEARCH_MAKEFILE_MARKER,
        "default_target": "slide",
        "hypo_preview_target": "hypo-template",
        "hypo_preview_source": str(preview),
    }


def validate_project_beamer_support(workspace: Path) -> JsonObject:
    root = project_root_from_workspace(workspace)
    installed: list[str] = []
    for source in BEAMER_RUNTIME_FILES:
        target = root / PROJECT_BEAMER_RELATIVE / source.relative_to(BEAMER_ASSET_ROOT)
        if not target.is_file():
            raise PaperSlidesError("Project-local Beamer runtime is missing; run prepare-slides again.")
        if sha256_file(target) != sha256_file(source):
            raise PaperSlidesError("Project-local Beamer runtime is stale; run prepare-slides again.")
        installed.append(target.relative_to(root).as_posix())
    return {
        "runtime_root": str(root / PROJECT_BEAMER_RELATIVE),
        "theme_path": str(root / PROJECT_THEME_RELATIVE),
        "bundle_fingerprint": beamer_bundle_fingerprint(),
        "runtime_files": installed,
    }


def normalize_figure_id(token: str) -> str:
    return f"Figure {token.upper()}"


def extract_figure_catalog(blocks: dict[str, list[JsonObject]]) -> list[JsonObject]:
    catalog: dict[str, JsonObject] = {}
    for locator, spans in sorted(blocks.items()):
        for span in spans:
            content = str(span.get("content") or "")
            for match in FIGURE_CAPTION_PATTERN.finditer(content):
                figure_id = normalize_figure_id(match.group(1))
                caption = " ".join(match.group(0).split())[:280]
                item = catalog.setdefault(
                    figure_id,
                    {"figure_id": figure_id, "caption": caption, "source_locators": []},
                )
                if locator not in item["source_locators"]:
                    item["source_locators"].append(locator)
    return [catalog[key] for key in sorted(catalog, key=lambda value: (len(value), value))]


def _figure_file_stem(figure_id: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", figure_id.casefold()).strip("-")


def _source_report(workspace: Path) -> JsonObject:
    report_path = resolve_artifact_path(workspace, PARSE_QUALITY_FILE)
    try:
        report = json.loads(report_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise PaperSlidesError(f"{PARSE_QUALITY_FILE} is missing or invalid.") from exc
    source = report.get("source")
    if not isinstance(source, dict):
        raise PaperSlidesError(f"{PARSE_QUALITY_FILE} has no source record.")
    return source


def _safe_source_asset(folder: Path, raw_path: str) -> Path | None:
    candidate = (folder / raw_path).resolve()
    try:
        candidate.relative_to(folder)
    except ValueError:
        return None
    if candidate.is_file():
        return candidate
    if candidate.suffix:
        return None
    for suffix in (".pdf", ".png", ".jpg", ".jpeg", ".webp", ".eps"):
        option = candidate.with_suffix(suffix)
        if option.is_file():
            return option
    return None


def _copy_or_render_latex_asset(source: Path, destination: Path) -> Path | None:
    """Materialize a browser-readable source asset inside the paper workspace."""
    suffix = source.suffix.casefold()
    if suffix in RASTER_IMAGE_SUFFIXES:
        target = destination.with_suffix(suffix)
        shutil.copyfile(source, target)
        return target
    if suffix != ".pdf":
        return None
    executable = shutil.which("pdftocairo")
    if executable is None:
        return None
    target = destination.with_suffix(".png")
    temporary = target.with_name(f".{target.stem}.tmp")
    try:
        completed = subprocess.run(
            [executable, "-png", "-singlefile", "-r", "180", str(source), str(temporary)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=90,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    rendered = Path(f"{temporary}.png")
    if completed.returncode != 0 or not rendered.is_file():
        rendered.unlink(missing_ok=True)
        return None
    rendered.replace(target)
    return target


def _latex_primary_graphics(expanded: str) -> list[str]:
    """Return primary Figure graphics in source order, including captionof figures."""
    entries: list[tuple[int, str]] = []
    occupied: list[tuple[int, int]] = []

    for match in LATEX_FIGURE_PATTERN.finditer(expanded):
        occupied.append((match.start(), match.end()))
        graphic = LATEX_GRAPHICS_PATTERN.search(match.group(0))
        if graphic is not None:
            entries.append((match.start(), graphic.group(1).strip()))

    graphics = list(LATEX_GRAPHICS_PATTERN.finditer(expanded))
    for index, graphic in enumerate(graphics):
        if any(start <= graphic.start() < end for start, end in occupied):
            continue
        next_graphic = graphics[index + 1].start() if index + 1 < len(graphics) else len(expanded)
        caption = LATEX_CAPTIONOF_FIGURE_PATTERN.search(expanded, graphic.end(), next_graphic)
        if caption is not None:
            entries.append((graphic.start(), graphic.group(1).strip()))

    return [asset for _, asset in sorted(entries)]


def _render_pdf_page(source: Path, page: int, destination: Path) -> Path | None:
    executable = shutil.which("pdftoppm")
    if executable is None or page < 1:
        return None
    if destination.exists():
        return destination
    temporary = destination.with_name(f".{destination.stem}.tmp")
    try:
        completed = subprocess.run(
            [
                executable,
                "-png",
                "-singlefile",
                "-r",
                "160",
                "-f",
                str(page),
                "-l",
                str(page),
                str(source),
                str(temporary),
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=90,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    rendered = Path(f"{temporary}.png")
    if completed.returncode != 0 or not rendered.is_file():
        rendered.unlink(missing_ok=True)
        return None
    rendered.replace(destination)
    return destination


def materialize_figure_assets(workspace: Path, figure_catalog: list[JsonObject]) -> list[JsonObject]:
    """Copy LaTeX figure assets, then fall back to faithful source-PDF page renders.

    The generated paths are intentionally local and ready to be inserted directly
    into a Figure placeholder. A page render is a fallback, not a claimed crop:
    it preserves the original paper visual when the LaTeX source has no reusable
    raster/vector asset for that Figure.
    """
    directory = Path(workspace)
    figures_directory = directory / FIGURES_DIR
    figures_directory.mkdir(exist_ok=True)
    source = _source_report(directory)
    result: dict[str, JsonObject] = {}

    # A LaTeX bundle gives the most precise image provenance. Figure numbering is
    # sequential in the source; only primary Figure N entries are mapped here.
    if source.get("input_kind") == "folder" and source.get("latex_entry"):
        folder = Path(str(source.get("locator") or "")).expanduser().resolve()
        entry = _safe_source_asset(folder, str(source.get("latex_entry") or ""))
        if entry is not None:
            try:
                from mw_paper_latex import _expand_inputs  # Local parser used by P2.

                expanded = _expand_inputs(entry)
                for number, asset_name in enumerate(_latex_primary_graphics(expanded), start=1):
                    figure_id = f"Figure {number}"
                    if not any(item["figure_id"] == figure_id for item in figure_catalog):
                        continue
                    asset = _safe_source_asset(entry.parent, asset_name)
                    if asset is None:
                        continue
                    target = _copy_or_render_latex_asset(
                        asset, figures_directory / f"{_figure_file_stem(figure_id)}-source"
                    )
                    if target is not None:
                        result[figure_id] = {
                            "figure_id": figure_id,
                            "path": target.relative_to(directory).as_posix(),
                            "kind": "latex-asset",
                            "source": asset.relative_to(folder).as_posix(),
                        }
            except (OSError, ValueError):
                # PDF page rendering below remains available for incomplete bundles.
                pass

    raw_pdf = resolve_artifact_path(directory, str(source.get("raw_artifact") or ""))
    if raw_pdf.is_file() and raw_pdf.suffix.casefold() == ".pdf":
        rendered_pages: dict[int, Path | None] = {}
        for figure in figure_catalog:
            figure_id = str(figure["figure_id"])
            if figure_id in result:
                continue
            pages = [
                int(match.group(1))
                for locator in figure.get("source_locators", [])
                if (match := re.fullmatch(r"pdf:p([1-9][0-9]*)", str(locator))) is not None
            ]
            if not pages:
                continue
            page = pages[0]
            if page not in rendered_pages:
                rendered_pages[page] = _render_pdf_page(
                    raw_pdf, page, figures_directory / f"source-page-{page}.png"
                )
            target = rendered_pages[page]
            if target is not None:
                result[figure_id] = {
                    "figure_id": figure_id,
                    "path": target.relative_to(directory).as_posix(),
                    "kind": "pdf-page-render",
                    "source": f"pdf:p{page}",
                }
    return [result[figure_id] for figure_id in sorted(result)]


def build_slides_context(
    workspace: Path,
    *,
    paper_id: str,
    source_format: str,
    source_fingerprint: str,
    read_output_fingerprint: str,
    summary_output_fingerprint: str,
) -> JsonObject:
    directory = Path(workspace)
    try:
        summary_validation = validate_summary(
            directory,
            paper_id=paper_id,
            source_format=source_format,
            source_fingerprint=source_fingerprint,
            read_output_fingerprint=read_output_fingerprint,
        )
        ledger = load_summary_ledger(resolve_artifact_path(directory, SUMMARY_LEDGER_FILE))
    except PaperSummaryError as exc:
        raise PaperSlidesError(str(exc)) from exc
    if summary_validation["summary_bundle_fingerprint"] != summary_output_fingerprint:
        raise PaperSlidesError(
            "Current summary.md + summary-ledger.json bytes do not match the completed summary stage."
        )
    claim_catalog = [
        {
            "claim_id": claim["claim_id"],
            "section": {
                "B": "background",
                "M": "method",
                "E": "experiments",
            }[claim["claim_id"][0]],
            "claim_text": claim["claim_text"],
        }
        for claim in ledger["claims"]
    ]
    try:
        _, blocks, locator_fingerprint = validate_source_locator_index(
            directory,
            paper_id=paper_id,
            source_format=source_format,
            source_fingerprint=source_fingerprint,
        )
    except SourceLocatorError as exc:
        raise PaperSlidesError(str(exc)) from exc
    try:
        asset_report = validate_beamer_assets()
    except ValueError as exc:
        raise PaperSlidesError(str(exc)) from exc

    figure_catalog = extract_figure_catalog(blocks)
    figure_assets = materialize_figure_assets(directory, figure_catalog)
    build_support = validate_paper_build_support(directory)
    metadata = summary_validation["metadata"]
    return {
        "slides_context_schema": SLIDES_CONTEXT_SCHEMA,
        "paper_id": paper_id,
        "inputs": {
            "summary": {
                "artifact": SUMMARY_FILE,
                "fingerprint": metadata["summary_body_fingerprint"],
            },
            "summary_ledger": {
                "artifact": SUMMARY_LEDGER_FILE,
                "fingerprint": metadata["summary_ledger_fingerprint"],
            },
            "summary_bundle": {"fingerprint": summary_output_fingerprint},
            "source_locators": {
                "artifact": SOURCE_LOCATOR_FILE,
                "fingerprint": locator_fingerprint,
            },
        },
        "presentation": {
            "theme": THEME_NAME,
            "engine": "xelatex",
            "theme_fingerprint": asset_report["bundle_fingerprint"],
            "size": "16:9",
            "math": "tex",
            "source_artifact": SLIDES_FILE,
            "pdf_artifact": PROJECT_PDF_RELATIVE.as_posix(),
            "figure_directory": FIGURES_DIR,
            "build": build_support,
            "lint_limits": {
                "max_pages": MAX_PAGES,
                "max_visible_characters_per_page": MAX_VISIBLE_CHARACTERS,
                "max_visible_lines_per_page": MAX_VISIBLE_LINES,
                "max_list_items_per_page": MAX_LIST_ITEMS,
                "max_code_lines_per_page": MAX_CODE_LINES,
            },
        },
        "claim_catalog": claim_catalog,
        "figure_catalog": figure_catalog,
        "figure_assets": figure_assets,
    }


def write_slides_context(
    workspace: Path,
    *,
    paper_id: str,
    source_format: str,
    source_fingerprint: str,
    read_output_fingerprint: str,
    summary_output_fingerprint: str,
) -> JsonObject:
    directory = Path(workspace)
    install_project_beamer_support(project_root_from_workspace(directory))
    install_paper_build_support(directory)
    context = build_slides_context(
        directory,
        paper_id=paper_id,
        source_format=source_format,
        source_fingerprint=source_fingerprint,
        read_output_fingerprint=read_output_fingerprint,
        summary_output_fingerprint=summary_output_fingerprint,
    )
    atomic_write_text(
        artifact_path(directory, SLIDES_CONTEXT_FILE, create_parent=True),
        json.dumps(context, ensure_ascii=False, indent=2) + "\n",
    )
    return context


def validate_slides_context(
    workspace: Path,
    *,
    paper_id: str,
    source_format: str,
    source_fingerprint: str,
    read_output_fingerprint: str,
    summary_output_fingerprint: str,
) -> tuple[JsonObject, str]:
    context_path = resolve_artifact_path(workspace, SLIDES_CONTEXT_FILE)
    if not context_path.is_file():
        raise PaperSlidesError(f"{SLIDES_CONTEXT_FILE} is missing; run prepare-slides first.")
    try:
        stored = json.loads(context_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise PaperSlidesError(f"{SLIDES_CONTEXT_FILE} is invalid: {exc}") from exc
    validate_project_beamer_support(workspace)
    expected = build_slides_context(
        workspace,
        paper_id=paper_id,
        source_format=source_format,
        source_fingerprint=source_fingerprint,
        read_output_fingerprint=read_output_fingerprint,
        summary_output_fingerprint=summary_output_fingerprint,
    )
    if stored != expected:
        raise PaperSlidesError(f"{SLIDES_CONTEXT_FILE} is stale or does not match current inputs.")
    return stored, sha256_file(context_path)


def strip_tex_comments(text: str) -> str:
    return TEX_COMMENT_PATTERN.sub("", text)


def page_claims(page: str, page_number: int) -> list[str]:
    declarations = CLAIMS_PATTERN.findall(page)
    if len(declarations) != 1:
        raise PaperSlidesError(
            f"{SLIDES_FILE} page {page_number} must contain exactly one "
            "% mary-claims: ... declaration."
        )
    tokens = [token for token in re.split(r"[\s,]+", declarations[0].strip()) if token]
    if not tokens or any(CLAIM_ID_PATTERN.fullmatch(token) is None for token in tokens):
        raise PaperSlidesError(f"{SLIDES_FILE} page {page_number} has an invalid claims declaration.")
    if len(set(tokens)) != len(tokens):
        raise PaperSlidesError(f"{SLIDES_FILE} page {page_number} has duplicate claim references.")
    return tokens


def validate_media_reference(workspace: Path, reference: str, page_number: int) -> None:
    value = reference.strip()
    if not value:
        return
    if re.match(r"^(?:https?:)?//", value, flags=re.IGNORECASE) or value.startswith("data:"):
        raise PaperSlidesError(
            f"{SLIDES_FILE} page {page_number} image references must be local repository files: "
            f"{value[:80]}"
        )
    path = PurePosixPath(value.replace("\\", "/"))
    if path.is_absolute() or ".." in path.parts:
        raise PaperSlidesError(f"{SLIDES_FILE} page {page_number} has an unsafe image reference: {value}")
    target = (Path(workspace) / path.as_posix()).resolve()
    try:
        target.relative_to(Path(workspace).resolve())
    except ValueError as exc:
        raise PaperSlidesError(
            f"{SLIDES_FILE} page {page_number} image escapes the paper workspace: {value}"
        ) from exc
    if not target.is_file():
        raise PaperSlidesError(f"{SLIDES_FILE} page {page_number} image does not exist: {value}")


def _read_braced(text: str, start: int) -> tuple[str, int]:
    if start >= len(text) or text[start] != "{":
        raise PaperSlidesError(f"{SLIDES_FILE} contains a malformed macro argument.")
    depth = 0
    escaped = False
    for index in range(start, len(text)):
        character = text[index]
        if escaped:
            escaped = False
            continue
        if character == "\\":
            escaped = True
            continue
        if character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1 : index], index + 1
    raise PaperSlidesError(f"{SLIDES_FILE} contains an unclosed macro argument.")


def extract_macro_calls(text: str, macro: str, arity: int) -> list[JsonObject]:
    calls: list[JsonObject] = []
    for match in re.finditer(re.escape(macro) + r"(?![A-Za-z@])", text):
        cursor = match.end()
        arguments: list[str] = []
        try:
            for _ in range(arity):
                while cursor < len(text) and text[cursor].isspace():
                    cursor += 1
                argument, cursor = _read_braced(text, cursor)
                arguments.append(argument)
        except PaperSlidesError as exc:
            raise PaperSlidesError(f"Malformed {macro} call in {SLIDES_FILE}.") from exc
        calls.append({"start": match.start(), "end": cursor, "arguments": arguments})
    return calls


def _without_macro_calls(text: str, calls: list[JsonObject]) -> str:
    result: list[str] = []
    cursor = 0
    for call in calls:
        result.append(text[cursor : int(call["start"])])
        cursor = int(call["end"])
    result.append(text[cursor:])
    return "".join(result)


def tex_to_plain(value: str) -> str:
    text = value
    for _ in range(4):
        updated = re.sub(
            r"\\(?:textbf|textit|emph|texttt|mathrm|operatorname)\s*\{([^{}]*)\}",
            r"\1",
            text,
        )
        if updated == text:
            break
        text = updated
    replacements = {
        r"\&": "&",
        r"\%": "%",
        r"\$": "$",
        r"\#": "#",
        r"\_": "_",
        r"\{": "{",
        r"\}": "}",
        "~": " ",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return " ".join(text.split())


def visible_page_metrics(page: str) -> JsonObject:
    visible = strip_tex_comments(page)
    list_items = len(re.findall(r"\\item(?:\[[^]]*\])?", visible))
    code_lines = 0
    for match in re.finditer(
        r"\\begin\{(?:verbatim|lstlisting)\}(.*?)\\end\{(?:verbatim|lstlisting)\}",
        visible,
        flags=re.DOTALL,
    ):
        code_lines += len([line for line in match.group(1).splitlines() if line.strip()])
    visible = re.sub(r"\\begin\{[^{}]+\}|\\end\{[^{}]+\}", " ", visible)
    visible = LATEX_COMMAND_PATTERN.sub(" ", visible)
    visible = visible.replace("{", " ").replace("}", " ")
    compact = re.sub(r"\s+", "", visible)
    visible_lines = [line for line in visible.splitlines() if line.strip()]
    return {
        "visible_characters": len(compact),
        "visible_lines": len(visible_lines),
        "list_items": list_items,
        "code_lines": code_lines,
    }


def validate_page_capacity(page: str, page_number: int) -> JsonObject:
    metrics = visible_page_metrics(page)
    limits = {
        "visible_characters": MAX_VISIBLE_CHARACTERS,
        "visible_lines": MAX_VISIBLE_LINES,
        "list_items": MAX_LIST_ITEMS,
        "code_lines": MAX_CODE_LINES,
    }
    for field, limit in limits.items():
        if metrics[field] > limit:
            raise PaperSlidesError(
                f"{SLIDES_FILE} page {page_number} exceeds {field} limit: "
                f"{metrics[field]} > {limit}."
            )
    return metrics


def _frame_title(match: re.Match[str], page_number: int) -> str:
    title = " ".join((match.group(1) or "").split())
    if not title:
        raise PaperSlidesError(f"{SLIDES_FILE} content page {page_number} requires a frame title.")
    return title


def _figure_metadata(page: str, page_number: int) -> list[JsonObject]:
    records: list[JsonObject] = []
    for payload in FIGURE_METADATA_PATTERN.findall(page):
        try:
            record = json.loads(payload)
        except json.JSONDecodeError as exc:
            raise PaperSlidesError(
                f"{SLIDES_FILE} page {page_number} has invalid mary-figure JSON: {exc}"
            ) from exc
        if not isinstance(record, dict) or set(record) != {"figure_id", "source_locator"}:
            raise PaperSlidesError(
                f"{SLIDES_FILE} page {page_number} mary-figure must contain exactly "
                "figure_id and source_locator."
            )
        records.append(record)
    return records


def validate_slides_document(workspace: Path, text: str, context: JsonObject) -> JsonObject:
    for label, token in REQUIRED_PREAMBLE.items():
        if text.count(token) != 1:
            raise PaperSlidesError(f"{SLIDES_FILE} requires exactly one {label}: {token}.")
    if text.count(ARTIFACT_MARKER) != 1:
        raise PaperSlidesError(f"{SLIDES_FILE} must contain exactly one {ARTIFACT_MARKER} marker.")
    if text.count(r"\begin{document}") != 1 or text.count(r"\end{document}") != 1:
        raise PaperSlidesError(f"{SLIDES_FILE} must contain one complete document environment.")
    if text.count(r"\VSPtitleframe") != 1:
        raise PaperSlidesError(f"{SLIDES_FILE} must contain exactly one VSP title frame.")
    if len(extract_macro_calls(text, r"\VSPendframe", 1)) != 1:
        raise PaperSlidesError(f"{SLIDES_FILE} must contain exactly one non-empty VSP end frame.")
    end_argument = extract_macro_calls(text, r"\VSPendframe", 1)[0]["arguments"][0]
    if not tex_to_plain(str(end_argument)):
        raise PaperSlidesError(f"{SLIDES_FILE} VSP end frame must have a non-empty closing title.")
    if not re.search(r"\\title(?:\[[^]]*\])?\s*\{\S", text):
        raise PaperSlidesError(f"{SLIDES_FILE} requires non-empty title metadata.")
    if not re.search(r"\\VSPsetspeaker(?:\[[^]]+\])?\s*\{[^{}]+\}\s*\{[^{}]+\}", text):
        raise PaperSlidesError(f"{SLIDES_FILE} requires non-empty VSP speaker metadata.")

    frame_matches = list(FRAME_PATTERN.finditer(text))
    section_frame_count = len(extract_macro_calls(text, r"\VSPsectionframe", 2))
    page_count = 2 + len(frame_matches) + section_frame_count
    if page_count < 6 or page_count > MAX_PAGES:
        raise PaperSlidesError(f"{SLIDES_FILE} must contain 6-{MAX_PAGES} pages; found {page_count}.")

    claim_sections = {item["claim_id"]: item["section"] for item in context["claim_catalog"]}
    figure_catalog = {item["figure_id"]: item for item in context["figure_catalog"]}
    figure_assets = {item["figure_id"]: item for item in context.get("figure_assets", [])}
    section_counts = {section: 0 for section in SECTION_ORDER}
    section_sequence: list[str] = []
    referenced_claims: set[str] = set()
    referenced_figures: set[str] = set()
    layout_pages = 0
    placeholder_count = 0
    image_reference_count = 0
    page_metrics: list[JsonObject] = []

    for frame_index, match in enumerate(frame_matches, start=1):
        page_number = frame_index + 1
        title = _frame_title(match, page_number)
        page = match.group(0)
        body = match.group(2)
        section_matches = [value.casefold() for value in SECTION_PATTERN.findall(page)]
        structural = bool(re.search(r"\\tableofcontents|%\s*mary-structural\b", page))
        if structural:
            if section_matches or CLAIMS_PATTERN.search(page):
                raise PaperSlidesError(
                    f"{SLIDES_FILE} structural page {page_number} must not declare section or claims."
                )
        else:
            if len(section_matches) != 1:
                raise PaperSlidesError(
                    f"{SLIDES_FILE} content page {page_number} requires exactly one "
                    "% mary-section declaration."
                )
            section = section_matches[0]
            section_counts[section] += 1
            section_sequence.append(section)
            claims = page_claims(page, page_number)
            for claim_id in claims:
                if claim_id not in claim_sections:
                    raise PaperSlidesError(
                        f"{SLIDES_FILE} page {page_number} references unknown summary claim {claim_id}."
                    )
                expected_prefix = SECTION_PREFIXES.get(section)
                if expected_prefix and not claim_id.startswith(expected_prefix):
                    raise PaperSlidesError(
                        f"{SLIDES_FILE} page {page_number} section {section} cannot cite {claim_id}."
                    )
                referenced_claims.add(claim_id)

        if VISIBLE_CLAIM_PATTERN.search(strip_tex_comments(page)):
            raise PaperSlidesError(
                f"{SLIDES_FILE} page {page_number} exposes summary claim ids; keep them in comments."
            )
        if r"\begin{columns}" in page or len(re.findall(r"\\begin\{minipage\}", page)) >= 2:
            layout_pages += 1

        metadata_records = _figure_metadata(page, page_number)
        figure_calls = extract_macro_calls(body, r"\MaryFigure", 3)
        if len(metadata_records) != len(figure_calls):
            raise PaperSlidesError(
                f"{SLIDES_FILE} page {page_number} must pair every mary-figure record with one MaryFigure call."
            )
        page_figure_ids: set[str] = set()
        for record, call in zip(metadata_records, figure_calls):
            asset_argument, id_argument, caption_argument = [str(value) for value in call["arguments"]]
            figure_id = str(record["figure_id"])
            if figure_id not in figure_catalog:
                raise PaperSlidesError(
                    f"{SLIDES_FILE} page {page_number} references unknown {figure_id or 'figure'}."
                )
            expected = figure_catalog[figure_id]
            if record["source_locator"] not in expected["source_locators"]:
                raise PaperSlidesError(
                    f"{SLIDES_FILE} page {page_number} locator does not resolve for {figure_id}."
                )
            if tex_to_plain(id_argument) != figure_id:
                raise PaperSlidesError(
                    f"{SLIDES_FILE} page {page_number} MaryFigure id does not match {figure_id}."
                )
            expected_caption = " ".join(str(expected["caption"]).split())
            if tex_to_plain(caption_argument) != expected_caption:
                raise PaperSlidesError(
                    f"{SLIDES_FILE} page {page_number} caption does not exactly match {figure_id} context."
                )
            expected_asset = figure_assets.get(figure_id)
            if expected_asset is not None and asset_argument != str(expected_asset["path"]):
                raise PaperSlidesError(
                    f"{SLIDES_FILE} page {page_number} {figure_id} must embed its prepared source asset: "
                    f"{expected_asset['path']}."
                )
            if expected_asset is None and asset_argument:
                raise PaperSlidesError(
                    f"{SLIDES_FILE} page {page_number} {figure_id} has no prepared source asset; "
                    "use an empty MaryFigure path."
                )
            if asset_argument:
                validate_media_reference(workspace, asset_argument, page_number)
                image_reference_count += 1
            page_figure_ids.add(figure_id)
            referenced_figures.add(figure_id)
            placeholder_count += 1

        page_without_figures = strip_tex_comments(_without_macro_calls(body, figure_calls))
        prose_figure_ids = {
            normalize_figure_id(token) for token in FIGURE_REFERENCE_PATTERN.findall(page_without_figures)
        }
        unknown_figures = sorted(prose_figure_ids - set(figure_catalog))
        if unknown_figures:
            raise PaperSlidesError(
                f"{SLIDES_FILE} page {page_number} references unknown figures: "
                + ", ".join(unknown_figures)
                + "."
            )
        missing_panels = sorted(prose_figure_ids - page_figure_ids)
        if missing_panels:
            raise PaperSlidesError(
                f"{SLIDES_FILE} page {page_number} references figures without MaryFigure panels: "
                + ", ".join(missing_panels)
                + "."
            )

        direct_images = list(
            re.finditer(r"\\includegraphics(?:\[([^]]*)\])?\s*\{([^{}]+)\}", strip_tex_comments(body))
        )
        for image in direct_images:
            options = image.group(1) or ""
            reference = image.group(2)
            if "keepaspectratio" not in options:
                raise PaperSlidesError(
                    f"{SLIDES_FILE} page {page_number} includegraphics must use keepaspectratio."
                )
            validate_media_reference(workspace, reference, page_number)
            image_reference_count += 1

        page_metrics.append(
            {"page": page_number, "title": title, **validate_page_capacity(page, page_number)}
        )

    ranks = [SECTION_ORDER.index(section) for section in section_sequence]
    if ranks != sorted(ranks):
        raise PaperSlidesError(
            f"{SLIDES_FILE} sections must progress background -> method -> experiments -> takeaways."
        )
    for required, minimum in (("background", 1), ("method", 2), ("experiments", 1)):
        if section_counts[required] < minimum:
            raise PaperSlidesError(
                f"{SLIDES_FILE} requires at least {minimum} {required} content page(s)."
            )
    if section_counts["method"] < max(section_counts["background"], section_counts["experiments"]):
        raise PaperSlidesError(
            f"{SLIDES_FILE} must keep Method at least as detailed as Background and Experiments."
        )
    if layout_pages < 2:
        raise PaperSlidesError(f"{SLIDES_FILE} must use Beamer multi-panel layouts on at least two pages.")
    if figure_catalog and placeholder_count == 0:
        raise PaperSlidesError(f"{SLIDES_FILE} must include at least one Figure from the catalog.")
    missing_claim_families = [
        prefix for prefix in ("B", "M", "E") if not any(claim.startswith(prefix) for claim in referenced_claims)
    ]
    if missing_claim_families:
        raise PaperSlidesError(
            f"{SLIDES_FILE} must cite background, method, and experiment claim families; missing: "
            + ", ".join(missing_claim_families)
            + "."
        )
    return {
        "page_count": page_count,
        "section_page_counts": section_counts,
        "layout_page_count": layout_pages,
        "claim_reference_count": len(referenced_claims),
        "referenced_claim_ids": sorted(referenced_claims),
        "figure_placeholder_count": placeholder_count,
        "image_reference_count": image_reference_count,
        "referenced_figure_ids": sorted(referenced_figures),
        "page_metrics": page_metrics,
    }


def validate_slides(
    workspace: Path,
    *,
    paper_id: str,
    source_format: str,
    source_fingerprint: str,
    read_output_fingerprint: str,
    summary_output_fingerprint: str,
) -> JsonObject:
    directory = Path(workspace)
    slides_path = directory / SLIDES_FILE
    if not slides_path.is_file():
        raise PaperSlidesError(f"{SLIDES_FILE} is missing.")
    context, context_fingerprint = validate_slides_context(
        directory,
        paper_id=paper_id,
        source_format=source_format,
        source_fingerprint=source_fingerprint,
        read_output_fingerprint=read_output_fingerprint,
        summary_output_fingerprint=summary_output_fingerprint,
    )
    report = validate_slides_document(directory, slides_path.read_text(encoding="utf-8"), context)
    return {
        "slides_fingerprint": sha256_file(slides_path),
        "metadata": {
            "slides_context_schema": SLIDES_CONTEXT_SCHEMA,
            "slides_context": SLIDES_CONTEXT_FILE,
            "slides_context_fingerprint": context_fingerprint,
            "theme": THEME_NAME,
            "theme_fingerprint": context["presentation"]["theme_fingerprint"],
            "engine": "xelatex",
            "math": "tex",
            "size": "16:9",
            **report,
        },
    }


def _pdf_page_count(pdf_path: Path) -> int:
    pdfinfo = shutil.which("pdfinfo")
    if pdfinfo is None:
        raise PaperSlidesError("Beamer PDF validation requires pdfinfo on PATH.")
    completed = subprocess.run(
        [pdfinfo, str(pdf_path)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        raise PaperSlidesError(f"pdfinfo failed: {' '.join(completed.stderr.split())[-400:]}")
    match = re.search(r"(?m)^Pages:\s+(\d+)\s*$", completed.stdout)
    if match is None:
        raise PaperSlidesError("pdfinfo did not report the Beamer page count.")
    return int(match.group(1))


def run_beamer_compile(workspace: Path) -> JsonObject:
    directory = Path(workspace).resolve()
    make = shutil.which("make")
    if make is None:
        raise PaperSlidesError("Beamer compilation requires GNU Make on PATH.")
    for command in ("latexmk", "xelatex"):
        if shutil.which(command) is None:
            raise PaperSlidesError(f"Beamer compilation requires {command} on PATH.")
    try:
        completed = subprocess.run(
            [make, "-B", "slide"],
            cwd=directory,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=180,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise PaperSlidesError("XeLaTeX Beamer compilation timed out after 180 seconds.") from exc
    pdf_path = directory / PROJECT_PDF_RELATIVE
    log_path = directory / PROJECT_LOG_RELATIVE
    if completed.returncode != 0 or not pdf_path.is_file() or not log_path.is_file():
        detail = " ".join((completed.stderr or completed.stdout).split())[-1000:]
        raise PaperSlidesError(f"XeLaTeX Beamer compilation failed: {detail or 'no output'}")
    return {
        "status": "passed",
        "runner": Path(make).name,
        "engine": "xelatex",
        "pdf_path": PROJECT_PDF_RELATIVE.as_posix(),
        "pdf_fingerprint": sha256_file(pdf_path),
        "log_path": PROJECT_LOG_RELATIVE.as_posix(),
        "page_count": _pdf_page_count(pdf_path),
    }


def run_beamer_pdf_audit(workspace: Path, *, expected_page_count: int | None = None) -> JsonObject:
    directory = Path(workspace).resolve()
    compile_report = run_beamer_compile(directory)
    if expected_page_count is not None and compile_report["page_count"] != expected_page_count:
        raise PaperSlidesError(
            "Beamer PDF page count does not match the linted source: "
            f"{compile_report['page_count']} != {expected_page_count}."
        )
    if not BEAMER_AUDIT_SCRIPT_PATH.is_file():
        raise PaperSlidesError("Bundled Beamer PDF audit script is missing.")
    try:
        completed = subprocess.run(
            [str(BEAMER_AUDIT_SCRIPT_PATH), str(directory / PROJECT_PDF_RELATIVE)],
            cwd=directory,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=180,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise PaperSlidesError("Beamer PDF audit timed out after 180 seconds.") from exc
    if completed.returncode != 0:
        detail = " ".join((completed.stderr or completed.stdout).split())[-1000:]
        raise PaperSlidesError(f"Beamer PDF audit failed: {detail or 'no output'}")
    slides_path = directory / SLIDES_FILE
    return {
        "status": "passed",
        "slides_fingerprint": sha256_file(slides_path),
        "audit_runner": BEAMER_AUDIT_SCRIPT_PATH.name,
        **compile_report,
    }
