#!/usr/bin/env python3
"""Grounded Marp slide artifacts and deterministic linting for Mary papers."""

from __future__ import annotations

from html import unescape
from html.parser import HTMLParser
import json
from pathlib import Path, PurePosixPath
import re
import shutil
import subprocess
import tempfile
from typing import Any

from mw_paper_artifacts import (
    PARSE_QUALITY_FILE,
    SLIDES_CONTEXT_FILE,
    SOURCE_LOCATOR_FILE,
    artifact_path,
    resolve_artifact_path,
)
from mw_paper_locators import SourceLocatorError, validate_source_locator_index
from mw_paper_sources import sha256_file
from mw_paper_summary import (
    PaperSummaryError,
    SUMMARY_FILE,
    SUMMARY_LEDGER_FILE,
    load_summary_ledger,
    validate_summary,
)
from mw_runtime import atomic_write_text


SLIDES_CONTEXT_SCHEMA = 1
SLIDES_FILE = "slides.md"
FIGURES_DIR = "figures"
PAPER_MAKEFILE = "Makefile"
HYPO_PREVIEW_DIR = "hypo-template-preview"
HYPO_PREVIEW_FILE = f"{HYPO_PREVIEW_DIR}/Slide.tex"
PAPER_MAKEFILE_MARKER = "# mary-paper-build:v1"
RESEARCH_MAKEFILE = Path(".mary-research") / "Makefile"
RESEARCH_MAKEFILE_MARKER = "# mary-research-build:v1"
THEME_NAME = "mary-shanghaitech-red"
PLUGIN_ROOT = Path(__file__).resolve().parents[1]
THEME_PATH = PLUGIN_ROOT / "assets" / "marp" / "themes" / f"{THEME_NAME}.css"
MARP_CONFIG_PATH = PLUGIN_ROOT / "assets" / "marp" / "marp.config.mjs"
IMAGE_OVERFLOW_AUDIT_SCRIPT_PATH = PLUGIN_ROOT / "scripts" / "mw_slide_image_overflow_audit.js"
IMAGE_OVERFLOW_BROWSER_PROBE_PATH = PLUGIN_ROOT / "scripts" / "mw_slide_browser_probe.mjs"
PROJECT_THEME_RELATIVE = Path(".mary-research") / "marp" / "themes" / f"{THEME_NAME}.css"
VSCODE_SETTINGS_RELATIVE = Path(".vscode") / "settings.json"
VSCODE_THEME_REFERENCE = f"./{PROJECT_THEME_RELATIVE.as_posix()}"

REQUIRED_FRONTMATTER = {
    "marp": "true",
    "theme": THEME_NAME,
    "size": "16:9",
    "math": "katex",
    "paginate": "true",
}
SECTION_ORDER = ("background", "method", "experiments", "takeaways")
SECTION_PREFIXES = {"background": "B", "method": "M", "experiments": "E"}
LAYOUT_CLASSES = {
    "cols-2",
    "cols-2-73",
    "cols-2-64",
    "cols-2-37",
    "cols-2-46",
    "cols-3",
    "rows-2",
    "rows-2-73",
    "rows-2-64",
    "rows-2-55",
    "rows-2-37",
    "rows-2-28",
    "pin-3",
}
IMAGE_PANEL_CLASSES = {"limg", "mimg", "rimg", "timg", "bimg"}
STRUCTURAL_CLASSES = {"trans", "toc_a", "toc_b"}
MAX_PAGES = 24
MAX_VISIBLE_CHARACTERS = 900
MAX_VISIBLE_LINES = 36
MAX_LIST_ITEMS = 8
MAX_CODE_LINES = 14
IMAGE_OVERFLOW_REVIEW_PX = 10.0
IMAGE_OVERFLOW_FAIL_PX = 50.0
RASTER_IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"}
LATEX_FIGURE_PATTERN = re.compile(
    r"\\begin\{(?:figure|figure\*)\}.*?\\end\{(?:figure|figure\*)\}", re.DOTALL
)
LATEX_GRAPHICS_PATTERN = re.compile(r"\\includegraphics(?:\[[^]]*\])?\s*\{([^{}]+)\}")
LATEX_CAPTIONOF_FIGURE_PATTERN = re.compile(
    r"\\captionof\s*\{\s*figure\s*\}\s*\{", re.IGNORECASE
)

PAPER_MAKEFILE_TEMPLATE = r'''# mary-paper-build:v1
# Generated by Mary Workflow. The existing slides.md is never rewritten by these targets.

PROJECT_ROOT := $(abspath $(CURDIR)/../../..)
SLIDES := slides.md
BUILD_DIR ?= build
THEME := $(PROJECT_ROOT)/.mary-research/marp/themes/mary-shanghaitech-red.css
MARP ?= npx @marp-team/marp-cli@4.3.1
MW_PAPER_SCRIPT ?= $(HOME)/.codex/skills/mary-workflow/scripts/mw_paper.py
PAPER_ID ?= $(notdir $(CURDIR))
HYPO_PATH ?= $(PROJECT_ROOT)/../Hypoxanthine-LaTeX
HYPO_PREVIEW := hypo-template-preview/Slide.tex

.PHONY: slide slides slide-html slide-pptx audit-slides audit hypo-template clean

slide slides: $(BUILD_DIR)/slides.pdf

$(BUILD_DIR)/slides.pdf: $(SLIDES) $(THEME)
	@mkdir -p "$(BUILD_DIR)"
	$(MARP) "$(SLIDES)" --theme-set "$(THEME)" --pdf --allow-local-files -o "$@"

slide-html: $(BUILD_DIR)/slides.html

$(BUILD_DIR)/slides.html: $(SLIDES) $(THEME)
	@mkdir -p "$(BUILD_DIR)"
	$(MARP) "$(SLIDES)" --theme-set "$(THEME)" --html --allow-local-files -o "$@"

slide-pptx: $(BUILD_DIR)/slides.pptx

$(BUILD_DIR)/slides.pptx: $(SLIDES) $(THEME)
	@mkdir -p "$(BUILD_DIR)"
	$(MARP) "$(SLIDES)" --theme-set "$(THEME)" --pptx --allow-local-files -o "$@"

audit-slides audit:
	@test -f "$(MW_PAPER_SCRIPT)" || (echo "Set MW_PAPER_SCRIPT to the Mary Workflow runtime."; exit 2)
	python3 "$(MW_PAPER_SCRIPT)" --project-root "$(PROJECT_ROOT)" lint-slides --paper-id "$(PAPER_ID)" --audit-overflow

# Compile a separate, original Hypoxanthine-LaTeX preview for visual comparison.
# This target never changes slides.md or build/slides.pdf.
hypo-template: $(BUILD_DIR)/hypo-template-preview.pdf

$(BUILD_DIR)/hypo-template-preview.pdf: $(HYPO_PREVIEW)
	@test -f "$(HYPO_PATH)/make/Hypoxanthine.mk" || (echo "Set HYPO_PATH to the Hypoxanthine-LaTeX checkout."; exit 2)
	$(MAKE) -f "$(HYPO_PATH)/make/Hypoxanthine.mk" HYPO_PATH="$(HYPO_PATH)" NAME=hypo-template-preview MAIN_FILE="$(CURDIR)/$(HYPO_PREVIEW)" OUT_DIR="$(CURDIR)/$(BUILD_DIR)/hypo-template-preview" SHELL_ESCAPE=1 all
	cp "$(BUILD_DIR)/hypo-template-preview/Slide.pdf" "$@"

clean:
	rm -rf "$(BUILD_DIR)"
'''

RESEARCH_MAKEFILE_TEMPLATE = r'''# mary-research-build:v1
# Generated by Mary Workflow. This dispatcher never rewrites any paper artifact.

RESEARCH_ROOT := $(abspath $(CURDIR))
PAPER_DIRS := $(wildcard $(RESEARCH_ROOT)/papers/*)
PAPER_IDS := $(notdir $(PAPER_DIRS))
PAPER_ID ?= $(firstword $(PAPER_IDS))
PAPER_DIR := $(RESEARCH_ROOT)/papers/$(PAPER_ID)
MW_PAPER_SCRIPT ?= $(HOME)/.codex/skills/mary-workflow/scripts/mw_paper.py

.PHONY: slide slides slide-html slide-pptx audit-slides audit hypo-template clean check

slide: check
	$(MAKE) -C "$(PAPER_DIR)" slide

slides: slide

slide-html: check
	$(MAKE) -C "$(PAPER_DIR)" slide-html

slide-pptx: check
	$(MAKE) -C "$(PAPER_DIR)" slide-pptx

audit-slides audit: check
	@test -f "$(MW_PAPER_SCRIPT)" || (echo "Set MW_PAPER_SCRIPT to the Mary Workflow runtime."; exit 2)
	python3 "$(MW_PAPER_SCRIPT)" --project-root "$(RESEARCH_ROOT)" lint-slides --paper-id "$(PAPER_ID)" --audit-overflow

hypo-template: check
	$(MAKE) -C "$(PAPER_DIR)" hypo-template

clean: check
	$(MAKE) -C "$(PAPER_DIR)" clean

check:
	@test -n "$(PAPER_ID)" || (echo "No paper workspace found under $(RESEARCH_ROOT)/papers."; exit 2)
	@test -d "$(PAPER_DIR)" || (echo "Unknown PAPER_ID=$(PAPER_ID); use make PAPER_ID=<paper-id> slide."; exit 2)
'''

HYPO_PREVIEW_TEMPLATE = r'''\documentclass[theme=school, aspectratio=169]{Hypo-Slide}

\HypoSlideSetup{
  title={GaussianFluent},
  subtitle={Original Hypoxanthine-LaTeX template preview},
  author={Bei Huang et al.},
  institute={ShanghaiTech University},
  date={2026}
}

\begin{document}

\frame{\titlepage}

\begin{frame}{Method at a glance}
  \begin{columns}[T]
    \begin{column}{0.48\textwidth}
      \begin{block}{Representation}
        Gaussian infilling adds internal particles so the representation can support volume-aware simulation.
      \end{block}
      \begin{block}{Physics}
        Mixed-material CD-MPM transfers state between Gaussian particles and an Eulerian grid.
      \end{block}
    \end{column}
    \begin{column}{0.48\textwidth}
      \begin{alertblock}{Key question}
        Does the same representation remain renderable after deformation and fracture?
      \end{alertblock}
      \[
        L_{total}=L_{MSE}+L_{SSIM}+\lambda\sum_i\lVert s_i\rVert_2^2
      \]
    \end{column}
  \end{columns}
\end{frame}

\begin{frame}{Original paper Figure 1}
  \centering
  \includegraphics[width=0.90\linewidth]{figures/figure-1-teaser.png}
\end{frame}

\end{document}
'''

ARTIFACT_MARKER = "<!-- mary-slides:v1 -->"
CLASS_PATTERN = re.compile(r"<!--\s*_class:\s*([^>]+?)\s*-->", flags=re.IGNORECASE)
SECTION_PATTERN = re.compile(
    r"<!--\s*section:\s*(background|method|experiments|takeaways)\s*-->",
    flags=re.IGNORECASE,
)
CLAIMS_PATTERN = re.compile(r"<!--\s*claims:\s*([^>]+?)\s*-->", flags=re.IGNORECASE)
CLAIM_ID_PATTERN = re.compile(r"[BME][0-9]{2,}")
VISIBLE_CLAIM_PATTERN = re.compile(r"\[([BME][0-9]{2,})\]")
COMMENT_PATTERN = re.compile(r"<!--.*?-->", flags=re.DOTALL)
HTML_TAG_PATTERN = re.compile(r"<[^>]+>")
MARKDOWN_IMAGE_PATTERN = re.compile(r"!\[[^\]]*\]\(([^)]+)\)")
CSS_URL_PATTERN = re.compile(r"url\(\s*(['\"]?)(.*?)\1\s*\)", flags=re.IGNORECASE)
HTML_VOID_TAGS = {
    "area",
    "base",
    "br",
    "col",
    "embed",
    "hr",
    "img",
    "input",
    "link",
    "meta",
    "param",
    "source",
    "track",
    "wbr",
}
FIGURE_CAPTION_PATTERN = re.compile(
    r"(?:\bfig(?:ure)?\.?|图)\s*([0-9]+(?:[a-z])?)\s*[:.\-]?\s*([^\n]{0,220})",
    flags=re.IGNORECASE,
)
FIGURE_REFERENCE_PATTERN = re.compile(
    r"(?:\bfig(?:ure)?\.?|图)\s*([0-9]+(?:[a-z])?)",
    flags=re.IGNORECASE,
)
FIGURE_CAPTION_NODE_PATTERN = re.compile(
    r"<[^>]*class=[\"'][^\"']*figure-placeholder__caption[^\"']*[\"'][^>]*>"
    r".*?</[^>]+>",
    flags=re.IGNORECASE | re.DOTALL,
)

JsonObject = dict[str, Any]


class PaperSlidesError(ValueError):
    """A slides input, reference, layout, or artifact violated the P5 contract."""


def project_root_from_workspace(workspace: Path) -> Path:
    directory = Path(workspace).resolve()
    if directory.parent.name != "papers" or directory.parent.parent.name != ".mary-research":
        raise PaperSlidesError(
            "Paper workspace must be <project>/.mary-research/papers/<paper-id>."
        )
    return directory.parents[2]


def strip_jsonc(text: str) -> str:
    """Remove JSONC comments and trailing commas without touching string contents."""
    output: list[str] = []
    index = 0
    in_string = False
    escaped = False
    while index < len(text):
        character = text[index]
        following = text[index + 1] if index + 1 < len(text) else ""
        if in_string:
            output.append(character)
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
            index += 1
            continue
        if character == '"':
            in_string = True
            output.append(character)
            index += 1
            continue
        if character == "/" and following == "/":
            output.extend("  ")
            index += 2
            while index < len(text) and text[index] not in "\r\n":
                output.append(" ")
                index += 1
            continue
        if character == "/" and following == "*":
            output.extend("  ")
            index += 2
            while index < len(text):
                if index + 1 < len(text) and text[index : index + 2] == "*/":
                    output.extend("  ")
                    index += 2
                    break
                output.append("\n" if text[index] == "\n" else " ")
                index += 1
            else:
                raise PaperSlidesError(".vscode/settings.json contains an unclosed block comment.")
            continue
        output.append(character)
        index += 1

    uncommented = "".join(output)
    result: list[str] = []
    index = 0
    in_string = False
    escaped = False
    while index < len(uncommented):
        character = uncommented[index]
        if in_string:
            result.append(character)
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
            index += 1
            continue
        if character == '"':
            in_string = True
            result.append(character)
            index += 1
            continue
        if character == ",":
            lookahead = index + 1
            while lookahead < len(uncommented) and uncommented[lookahead].isspace():
                lookahead += 1
            if lookahead < len(uncommented) and uncommented[lookahead] in "]}":
                index += 1
                continue
        result.append(character)
        index += 1
    return "".join(result)


def load_vscode_settings(path: Path) -> JsonObject:
    if not path.is_file():
        return {}
    try:
        payload = json.loads(strip_jsonc(path.read_text(encoding="utf-8")))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise PaperSlidesError(f"Cannot merge invalid {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise PaperSlidesError(f"Cannot merge {path}: top-level value must be an object.")
    return payload


def required_vscode_settings(settings: JsonObject) -> JsonObject:
    merged = dict(settings)
    themes = merged.get("markdown.marp.themes", [])
    if not isinstance(themes, list) or any(not isinstance(value, str) for value in themes):
        raise PaperSlidesError(
            ".vscode/settings.json markdown.marp.themes must be an array of strings."
        )
    merged["markdown.marp.html"] = "all"
    merged["markdown.marp.mathTypesetting"] = "katex"
    merged["markdown.marp.themes"] = [
        *(value for value in themes if value != VSCODE_THEME_REFERENCE),
        VSCODE_THEME_REFERENCE,
    ]
    return merged


def install_project_marp_support(project_root: Path) -> JsonObject:
    """Install the offline theme and VS Code registration into a target project."""
    root = Path(project_root).resolve()
    if not THEME_PATH.is_file():
        raise PaperSlidesError(f"Localized Marp theme is missing: {THEME_PATH}")
    settings_path = root / VSCODE_SETTINGS_RELATIVE
    settings = load_vscode_settings(settings_path)
    merged = required_vscode_settings(settings)

    theme_target = root / PROJECT_THEME_RELATIVE
    theme_target.parent.mkdir(parents=True, exist_ok=True)
    source_fingerprint = sha256_file(THEME_PATH)
    if not theme_target.is_file() or sha256_file(theme_target) != source_fingerprint:
        atomic_write_text(theme_target, THEME_PATH.read_text(encoding="utf-8"))

    if settings != merged:
        settings_path.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text(
            settings_path,
            json.dumps(merged, ensure_ascii=False, indent=2) + "\n",
        )
    return {
        "theme_path": str(theme_target),
        "theme_reference": VSCODE_THEME_REFERENCE,
        "theme_fingerprint": source_fingerprint,
        "vscode_settings": str(settings_path),
    }


def install_paper_build_support(workspace: Path) -> JsonObject:
    """Install a reproducible Marp Makefile and isolated Hypo preview source."""
    directory = Path(workspace).resolve()
    project_root = project_root_from_workspace(directory)
    research_makefile = project_root / RESEARCH_MAKEFILE
    if research_makefile.is_file() and RESEARCH_MAKEFILE_MARKER not in research_makefile.read_text(encoding="utf-8"):
        raise PaperSlidesError(
            f"Existing {research_makefile} is not a Mary-generated research build file; "
            "move it aside before prepare-slides installs the managed target."
        )
    if not research_makefile.is_file() or research_makefile.read_text(encoding="utf-8") != RESEARCH_MAKEFILE_TEMPLATE:
        atomic_write_text(research_makefile, RESEARCH_MAKEFILE_TEMPLATE)

    makefile = directory / PAPER_MAKEFILE
    if makefile.is_file() and PAPER_MAKEFILE_MARKER not in makefile.read_text(encoding="utf-8"):
        raise PaperSlidesError(
            f"Existing {makefile} is not a Mary-generated paper build file; "
            "move it aside before prepare-slides installs the managed target."
        )
    if not makefile.is_file() or makefile.read_text(encoding="utf-8") != PAPER_MAKEFILE_TEMPLATE:
        atomic_write_text(makefile, PAPER_MAKEFILE_TEMPLATE)

    preview = directory / HYPO_PREVIEW_FILE
    preview.parent.mkdir(parents=True, exist_ok=True)
    if not preview.is_file() or preview.read_text(encoding="utf-8") != HYPO_PREVIEW_TEMPLATE:
        atomic_write_text(preview, HYPO_PREVIEW_TEMPLATE)
    return {
        "makefile": str(makefile),
        "makefile_marker": PAPER_MAKEFILE_MARKER,
        "research_makefile": str(research_makefile),
        "research_makefile_marker": RESEARCH_MAKEFILE_MARKER,
        "default_target": "slide",
        "hypo_preview_target": "hypo-template",
        "hypo_preview_source": str(preview),
    }


def validate_paper_build_support(workspace: Path) -> JsonObject:
    """Verify the generated paper-local build entrypoints without rewriting them."""
    directory = Path(workspace).resolve()
    project_root = project_root_from_workspace(directory)
    research_makefile = project_root / RESEARCH_MAKEFILE
    if not research_makefile.is_file() or RESEARCH_MAKEFILE_MARKER not in research_makefile.read_text(encoding="utf-8"):
        raise PaperSlidesError("Project .mary-research Makefile is missing or stale; run prepare-slides again.")
    makefile = directory / PAPER_MAKEFILE
    preview = directory / HYPO_PREVIEW_FILE
    if not makefile.is_file() or PAPER_MAKEFILE_MARKER not in makefile.read_text(encoding="utf-8"):
        raise PaperSlidesError("Paper Makefile is missing or stale; run prepare-slides again.")
    if not preview.is_file() or "Hypo-Slide" not in preview.read_text(encoding="utf-8"):
        raise PaperSlidesError("Hypo template preview source is missing or stale; run prepare-slides again.")
    return {
        "makefile": str(makefile),
        "makefile_marker": PAPER_MAKEFILE_MARKER,
        "research_makefile": str(research_makefile),
        "research_makefile_marker": RESEARCH_MAKEFILE_MARKER,
        "default_target": "slide",
        "hypo_preview_target": "hypo-template",
        "hypo_preview_source": str(preview),
    }


def validate_project_marp_support(workspace: Path) -> JsonObject:
    root = project_root_from_workspace(workspace)
    theme_target = root / PROJECT_THEME_RELATIVE
    if not theme_target.is_file():
        raise PaperSlidesError("Project-local Marp theme is missing; run prepare-slides again.")
    source_fingerprint = sha256_file(THEME_PATH)
    if sha256_file(theme_target) != source_fingerprint:
        raise PaperSlidesError("Project-local Marp theme is stale; run prepare-slides again.")
    settings_path = root / VSCODE_SETTINGS_RELATIVE
    settings = load_vscode_settings(settings_path)
    if required_vscode_settings(settings) != settings:
        raise PaperSlidesError(
            "Project VS Code Marp settings are missing or stale; run prepare-slides again."
        )
    return {
        "theme_path": str(theme_target),
        "theme_reference": VSCODE_THEME_REFERENCE,
        "theme_fingerprint": source_fingerprint,
        "vscode_settings": str(settings_path),
    }


def normalize_figure_id(token: str) -> str:
    return f"Figure {token.upper()}"


def extract_figure_catalog(blocks: dict[str, list[JsonObject]]) -> list[JsonObject]:
    catalog: dict[str, JsonObject] = {}
    for locator, spans in sorted(blocks.items()):
        for span in spans:
            content = str(span.get("content") or "")
            for match in FIGURE_CAPTION_PATTERN.finditer(content):
                figure_id = normalize_figure_id(match.group(1))
                caption = " ".join(match.group(0).split())[:280]
                item = catalog.setdefault(
                    figure_id,
                    {"figure_id": figure_id, "caption": caption, "source_locators": []},
                )
                if locator not in item["source_locators"]:
                    item["source_locators"].append(locator)
    return [catalog[key] for key in sorted(catalog, key=lambda value: (len(value), value))]


def _figure_file_stem(figure_id: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", figure_id.casefold()).strip("-")


def _source_report(workspace: Path) -> JsonObject:
    report_path = resolve_artifact_path(workspace, PARSE_QUALITY_FILE)
    try:
        report = json.loads(report_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise PaperSlidesError(f"{PARSE_QUALITY_FILE} is missing or invalid.") from exc
    source = report.get("source")
    if not isinstance(source, dict):
        raise PaperSlidesError(f"{PARSE_QUALITY_FILE} has no source record.")
    return source


def _safe_source_asset(folder: Path, raw_path: str) -> Path | None:
    candidate = (folder / raw_path).resolve()
    try:
        candidate.relative_to(folder)
    except ValueError:
        return None
    if candidate.is_file():
        return candidate
    if candidate.suffix:
        return None
    for suffix in (".pdf", ".png", ".jpg", ".jpeg", ".webp", ".eps"):
        option = candidate.with_suffix(suffix)
        if option.is_file():
            return option
    return None


def _copy_or_render_latex_asset(source: Path, destination: Path) -> Path | None:
    """Materialize a browser-readable source asset inside the paper workspace."""
    suffix = source.suffix.casefold()
    if suffix in RASTER_IMAGE_SUFFIXES:
        target = destination.with_suffix(suffix)
        shutil.copyfile(source, target)
        return target
    if suffix != ".pdf":
        return None
    executable = shutil.which("pdftocairo")
    if executable is None:
        return None
    target = destination.with_suffix(".png")
    temporary = target.with_name(f".{target.stem}.tmp")
    try:
        completed = subprocess.run(
            [executable, "-png", "-singlefile", "-r", "180", str(source), str(temporary)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=90,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    rendered = Path(f"{temporary}.png")
    if completed.returncode != 0 or not rendered.is_file():
        rendered.unlink(missing_ok=True)
        return None
    rendered.replace(target)
    return target


def _latex_primary_graphics(expanded: str) -> list[str]:
    """Return primary Figure graphics in source order, including captionof figures."""
    entries: list[tuple[int, str]] = []
    occupied: list[tuple[int, int]] = []

    for match in LATEX_FIGURE_PATTERN.finditer(expanded):
        occupied.append((match.start(), match.end()))
        graphic = LATEX_GRAPHICS_PATTERN.search(match.group(0))
        if graphic is not None:
            entries.append((match.start(), graphic.group(1).strip()))

    graphics = list(LATEX_GRAPHICS_PATTERN.finditer(expanded))
    for index, graphic in enumerate(graphics):
        if any(start <= graphic.start() < end for start, end in occupied):
            continue
        next_graphic = graphics[index + 1].start() if index + 1 < len(graphics) else len(expanded)
        caption = LATEX_CAPTIONOF_FIGURE_PATTERN.search(expanded, graphic.end(), next_graphic)
        if caption is not None:
            entries.append((graphic.start(), graphic.group(1).strip()))

    return [asset for _, asset in sorted(entries)]


def _render_pdf_page(source: Path, page: int, destination: Path) -> Path | None:
    executable = shutil.which("pdftoppm")
    if executable is None or page < 1:
        return None
    if destination.exists():
        return destination
    temporary = destination.with_name(f".{destination.stem}.tmp")
    try:
        completed = subprocess.run(
            [
                executable,
                "-png",
                "-singlefile",
                "-r",
                "160",
                "-f",
                str(page),
                "-l",
                str(page),
                str(source),
                str(temporary),
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=90,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    rendered = Path(f"{temporary}.png")
    if completed.returncode != 0 or not rendered.is_file():
        rendered.unlink(missing_ok=True)
        return None
    rendered.replace(destination)
    return destination


def materialize_figure_assets(workspace: Path, figure_catalog: list[JsonObject]) -> list[JsonObject]:
    """Copy LaTeX figure assets, then fall back to faithful source-PDF page renders.

    The generated paths are intentionally local and ready to be inserted directly
    into a Figure placeholder. A page render is a fallback, not a claimed crop:
    it preserves the original paper visual when the LaTeX source has no reusable
    raster/vector asset for that Figure.
    """
    directory = Path(workspace)
    figures_directory = directory / FIGURES_DIR
    figures_directory.mkdir(exist_ok=True)
    source = _source_report(directory)
    result: dict[str, JsonObject] = {}

    # A LaTeX bundle gives the most precise image provenance. Figure numbering is
    # sequential in the source; only primary Figure N entries are mapped here.
    if source.get("input_kind") == "folder" and source.get("latex_entry"):
        folder = Path(str(source.get("locator") or "")).expanduser().resolve()
        entry = _safe_source_asset(folder, str(source.get("latex_entry") or ""))
        if entry is not None:
            try:
                from mw_paper_latex import _expand_inputs  # Local parser used by P2.

                expanded = _expand_inputs(entry)
                for number, asset_name in enumerate(_latex_primary_graphics(expanded), start=1):
                    figure_id = f"Figure {number}"
                    if not any(item["figure_id"] == figure_id for item in figure_catalog):
                        continue
                    asset = _safe_source_asset(entry.parent, asset_name)
                    if asset is None:
                        continue
                    target = _copy_or_render_latex_asset(
                        asset, figures_directory / f"{_figure_file_stem(figure_id)}-source"
                    )
                    if target is not None:
                        result[figure_id] = {
                            "figure_id": figure_id,
                            "path": target.relative_to(directory).as_posix(),
                            "kind": "latex-asset",
                            "source": asset.relative_to(folder).as_posix(),
                        }
            except (OSError, ValueError):
                # PDF page rendering below remains available for incomplete bundles.
                pass

    raw_pdf = resolve_artifact_path(directory, str(source.get("raw_artifact") or ""))
    if raw_pdf.is_file() and raw_pdf.suffix.casefold() == ".pdf":
        rendered_pages: dict[int, Path | None] = {}
        for figure in figure_catalog:
            figure_id = str(figure["figure_id"])
            if figure_id in result:
                continue
            pages = [
                int(match.group(1))
                for locator in figure.get("source_locators", [])
                if (match := re.fullmatch(r"pdf:p([1-9][0-9]*)", str(locator))) is not None
            ]
            if not pages:
                continue
            page = pages[0]
            if page not in rendered_pages:
                rendered_pages[page] = _render_pdf_page(
                    raw_pdf, page, figures_directory / f"source-page-{page}.png"
                )
            target = rendered_pages[page]
            if target is not None:
                result[figure_id] = {
                    "figure_id": figure_id,
                    "path": target.relative_to(directory).as_posix(),
                    "kind": "pdf-page-render",
                    "source": f"pdf:p{page}",
                }
    return [result[figure_id] for figure_id in sorted(result)]


def build_slides_context(
    workspace: Path,
    *,
    paper_id: str,
    source_format: str,
    source_fingerprint: str,
    read_output_fingerprint: str,
    summary_output_fingerprint: str,
) -> JsonObject:
    directory = Path(workspace)
    try:
        summary_validation = validate_summary(
            directory,
            paper_id=paper_id,
            source_format=source_format,
            source_fingerprint=source_fingerprint,
            read_output_fingerprint=read_output_fingerprint,
        )
        ledger = load_summary_ledger(resolve_artifact_path(directory, SUMMARY_LEDGER_FILE))
    except PaperSummaryError as exc:
        raise PaperSlidesError(str(exc)) from exc
    if summary_validation["summary_bundle_fingerprint"] != summary_output_fingerprint:
        raise PaperSlidesError(
            "Current summary.md + summary-ledger.json bytes do not match the completed summary stage."
        )
    claim_catalog = [
        {
            "claim_id": claim["claim_id"],
            "section": {
                "B": "background",
                "M": "method",
                "E": "experiments",
            }[claim["claim_id"][0]],
            "claim_text": claim["claim_text"],
        }
        for claim in ledger["claims"]
    ]
    try:
        _, blocks, locator_fingerprint = validate_source_locator_index(
            directory,
            paper_id=paper_id,
            source_format=source_format,
            source_fingerprint=source_fingerprint,
        )
    except SourceLocatorError as exc:
        raise PaperSlidesError(str(exc)) from exc
    if not THEME_PATH.is_file():
        raise PaperSlidesError(f"Localized Marp theme is missing: {THEME_PATH}")

    figure_catalog = extract_figure_catalog(blocks)
    figure_assets = materialize_figure_assets(directory, figure_catalog)
    build_support = validate_paper_build_support(directory)
    metadata = summary_validation["metadata"]
    return {
        "slides_context_schema": SLIDES_CONTEXT_SCHEMA,
        "paper_id": paper_id,
        "inputs": {
            "summary": {
                "artifact": SUMMARY_FILE,
                "fingerprint": metadata["summary_body_fingerprint"],
            },
            "summary_ledger": {
                "artifact": SUMMARY_LEDGER_FILE,
                "fingerprint": metadata["summary_ledger_fingerprint"],
            },
            "summary_bundle": {"fingerprint": summary_output_fingerprint},
            "source_locators": {
                "artifact": SOURCE_LOCATOR_FILE,
                "fingerprint": locator_fingerprint,
            },
        },
        "presentation": {
            "theme": THEME_NAME,
            "theme_fingerprint": sha256_file(THEME_PATH),
            "size": "16:9",
            "math": "katex",
            "figure_directory": FIGURES_DIR,
            "build": build_support,
            "lint_limits": {
                "max_pages": MAX_PAGES,
                "max_visible_characters_per_page": MAX_VISIBLE_CHARACTERS,
                "max_visible_lines_per_page": MAX_VISIBLE_LINES,
                "max_list_items_per_page": MAX_LIST_ITEMS,
                "max_code_lines_per_page": MAX_CODE_LINES,
            },
        },
        "claim_catalog": claim_catalog,
        "figure_catalog": figure_catalog,
        "figure_assets": figure_assets,
    }


def write_slides_context(
    workspace: Path,
    *,
    paper_id: str,
    source_format: str,
    source_fingerprint: str,
    read_output_fingerprint: str,
    summary_output_fingerprint: str,
) -> JsonObject:
    directory = Path(workspace)
    install_project_marp_support(project_root_from_workspace(directory))
    install_paper_build_support(directory)
    context = build_slides_context(
        directory,
        paper_id=paper_id,
        source_format=source_format,
        source_fingerprint=source_fingerprint,
        read_output_fingerprint=read_output_fingerprint,
        summary_output_fingerprint=summary_output_fingerprint,
    )
    atomic_write_text(
        artifact_path(directory, SLIDES_CONTEXT_FILE, create_parent=True),
        json.dumps(context, ensure_ascii=False, indent=2) + "\n",
    )
    return context


def validate_slides_context(
    workspace: Path,
    *,
    paper_id: str,
    source_format: str,
    source_fingerprint: str,
    read_output_fingerprint: str,
    summary_output_fingerprint: str,
) -> tuple[JsonObject, str]:
    context_path = resolve_artifact_path(workspace, SLIDES_CONTEXT_FILE)
    if not context_path.is_file():
        raise PaperSlidesError(f"{SLIDES_CONTEXT_FILE} is missing; run prepare-slides first.")
    try:
        stored = json.loads(context_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise PaperSlidesError(f"{SLIDES_CONTEXT_FILE} is invalid: {exc}") from exc
    validate_project_marp_support(workspace)
    expected = build_slides_context(
        workspace,
        paper_id=paper_id,
        source_format=source_format,
        source_fingerprint=source_fingerprint,
        read_output_fingerprint=read_output_fingerprint,
        summary_output_fingerprint=summary_output_fingerprint,
    )
    if stored != expected:
        raise PaperSlidesError(f"{SLIDES_CONTEXT_FILE} is stale or does not match current inputs.")
    return stored, sha256_file(context_path)


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise PaperSlidesError("slides.md must begin with YAML frontmatter.")
    try:
        end = next(index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---")
    except StopIteration as exc:
        raise PaperSlidesError("slides.md frontmatter is not closed by ---.") from exc
    frontmatter: dict[str, str] = {}
    for line in lines[1:end]:
        if not line.strip():
            continue
        if ":" not in line:
            raise PaperSlidesError(f"slides.md frontmatter line is not key: value: {line}")
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if not key or key in frontmatter:
            raise PaperSlidesError(f"slides.md frontmatter has an empty or duplicate key: {key}")
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        frontmatter[key] = value
    for key, expected in REQUIRED_FRONTMATTER.items():
        if frontmatter.get(key, "").casefold() != expected.casefold():
            raise PaperSlidesError(f"slides.md frontmatter requires {key}: {expected}.")
    return frontmatter, "\n".join(lines[end + 1 :]).strip()


def page_classes(page: str) -> set[str]:
    classes: set[str] = set()
    for declaration in CLASS_PATTERN.findall(page):
        classes.update(declaration.split())
    return classes


def page_claims(page: str, page_number: int) -> list[str]:
    declarations = CLAIMS_PATTERN.findall(page)
    if len(declarations) != 1:
        raise PaperSlidesError(
            f"slides.md page {page_number} must contain exactly one <!-- claims: ... --> declaration."
        )
    tokens = [token for token in re.split(r"[\s,]+", declarations[0].strip()) if token]
    if not tokens or any(CLAIM_ID_PATTERN.fullmatch(token) is None for token in tokens):
        raise PaperSlidesError(f"slides.md page {page_number} has an invalid claims declaration.")
    if len(set(tokens)) != len(tokens):
        raise PaperSlidesError(f"slides.md page {page_number} has duplicate claim references.")
    return tokens


class SlideHTMLInspector(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.placeholders: list[JsonObject] = []
        self.image_sources: list[str] = []
        self._active: JsonObject | None = None
        self._stack: list[str] = []
        self._caption_depth: int | None = None

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self._handle_start(tag, attrs, self_closing=tag.casefold() in HTML_VOID_TAGS)

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self._handle_start(tag, attrs, self_closing=True)

    def _handle_start(
        self,
        tag: str,
        attrs: list[tuple[str, str | None]],
        *,
        self_closing: bool,
    ) -> None:
        attributes = {name: value or "" for name, value in attrs}
        classes = set(attributes.get("class", "").split())
        normalized_tag = tag.casefold()
        if normalized_tag == "img":
            self.image_sources.append(attributes.get("src", ""))
        if self._active is not None:
            if normalized_tag == "img":
                self._active.setdefault("image_sources", []).append(attributes.get("src", ""))
            if not self_closing:
                self._stack.append(normalized_tag)
            if "figure-placeholder__number" in classes:
                self._active["has_number_node"] = True
            if "figure-placeholder__caption" in classes:
                self._active["has_caption_node"] = True
                self._caption_depth = len(self._stack)
            return
        if normalized_tag == "div" and "figure-placeholder" in classes:
            self._active = {
                "figure_id": attributes.get("data-figure", ""),
                "source_locator": attributes.get("data-source-locator", ""),
                "classes": sorted(classes),
                "has_number_node": False,
                "has_caption_node": False,
                "image_sources": [],
                "text": [],
                "caption_text": [],
            }
            self._stack = [normalized_tag]
            self._caption_depth = None

    def handle_endtag(self, tag: str) -> None:
        if self._active is None:
            return
        normalized_tag = tag.casefold()
        if normalized_tag in HTML_VOID_TAGS:
            return
        if not self._stack:
            raise PaperSlidesError("slides.md contains an unexpected HTML closing tag.")
        if self._stack[-1] != normalized_tag:
            raise PaperSlidesError(
                f"slides.md contains mismatched HTML tags: expected </{self._stack[-1]}> but found </{normalized_tag}>."
            )
        self._stack.pop()
        if self._caption_depth is not None and len(self._stack) < self._caption_depth:
            self._caption_depth = None
        if not self._stack:
            self._active["text"] = " ".join(" ".join(self._active["text"]).split())
            self._active["caption_text"] = " ".join(
                " ".join(self._active["caption_text"]).split()
            )
            self.placeholders.append(self._active)
            self._active = None

    def handle_data(self, data: str) -> None:
        if self._active is not None:
            self._active["text"].append(data)
            if self._caption_depth is not None and len(self._stack) >= self._caption_depth:
                self._active["caption_text"].append(data)

    def close(self) -> None:
        super().close()
        if self._active is not None:
            raise PaperSlidesError(
                "slides.md contains an unclosed HTML element or figure-placeholder div."
            )


def validate_media_reference(workspace: Path, reference: str, page_number: int) -> None:
    value = reference.strip().strip("<>")
    if not value:
        raise PaperSlidesError(f"slides.md page {page_number} contains an empty image reference.")
    if re.match(r"^(?:https?:)?//", value, flags=re.IGNORECASE) or value.startswith("data:"):
        raise PaperSlidesError(
            f"slides.md page {page_number} image references must be local repository files: {value[:80]}"
        )
    path = PurePosixPath(value.replace("\\", "/"))
    if path.is_absolute() or ".." in path.parts:
        raise PaperSlidesError(f"slides.md page {page_number} has an unsafe image reference: {value}")
    target = (Path(workspace) / path.as_posix()).resolve()
    try:
        target.relative_to(Path(workspace).resolve())
    except ValueError as exc:
        raise PaperSlidesError(f"slides.md page {page_number} image escapes the paper workspace: {value}") from exc
    if not target.is_file():
        raise PaperSlidesError(f"slides.md page {page_number} image does not exist: {value}")


def visible_page_metrics(page: str) -> JsonObject:
    without_comments = COMMENT_PATTERN.sub("", page)
    without_tags = HTML_TAG_PATTERN.sub(" ", without_comments)
    visible = unescape(without_tags)
    compact = re.sub(r"\s+", "", visible)
    visible_lines = [line for line in visible.splitlines() if line.strip()]
    list_items = len(re.findall(r"(?m)^\s*(?:[-*+]|\d+[.)])\s+", visible))
    code_lines = 0
    in_code = False
    for line in visible.splitlines():
        if line.strip().startswith("```"):
            in_code = not in_code
        elif in_code and line.strip():
            code_lines += 1
    return {
        "visible_characters": len(compact),
        "visible_lines": len(visible_lines),
        "list_items": list_items,
        "code_lines": code_lines,
    }


def validate_page_capacity(page: str, page_number: int) -> JsonObject:
    metrics = visible_page_metrics(page)
    limits = {
        "visible_characters": MAX_VISIBLE_CHARACTERS,
        "visible_lines": MAX_VISIBLE_LINES,
        "list_items": MAX_LIST_ITEMS,
        "code_lines": MAX_CODE_LINES,
    }
    for field, limit in limits.items():
        if metrics[field] > limit:
            raise PaperSlidesError(
                f"slides.md page {page_number} exceeds {field} limit: {metrics[field]} > {limit}."
            )
    return metrics


def validate_slides_document(workspace: Path, text: str, context: JsonObject) -> JsonObject:
    _, body = parse_frontmatter(text)
    if body.count(ARTIFACT_MARKER) != 1:
        raise PaperSlidesError(f"slides.md must contain exactly one {ARTIFACT_MARKER} marker.")
    pages = [page.strip() for page in re.split(r"(?m)^---[ \t]*$", body)]
    if any(not page for page in pages):
        raise PaperSlidesError("slides.md contains an empty slide.")
    if len(pages) < 6 or len(pages) > MAX_PAGES:
        raise PaperSlidesError(f"slides.md must contain 6-{MAX_PAGES} slides; found {len(pages)}.")

    claim_sections = {item["claim_id"]: item["section"] for item in context["claim_catalog"]}
    figure_catalog = {item["figure_id"]: item for item in context["figure_catalog"]}
    figure_assets = {item["figure_id"]: item for item in context.get("figure_assets", [])}
    section_counts = {section: 0 for section in SECTION_ORDER}
    section_sequence: list[str] = []
    referenced_claims: set[str] = set()
    referenced_figures: set[str] = set()
    layout_pages = 0
    placeholder_count = 0
    image_reference_count = 0
    page_metrics: list[JsonObject] = []

    for index, page in enumerate(pages):
        page_number = index + 1
        classes = page_classes(page)
        headings_h1 = re.findall(r"(?m)^#[ \t]+\S.*$", page)
        headings_h2 = re.findall(r"(?m)^##[ \t]+\S.*$", page)
        if index == 0:
            if "cover_e" not in classes or len(headings_h1) != 1:
                raise PaperSlidesError("slides.md first slide must be a cover_e page with exactly one H1 title.")
            if SECTION_PATTERN.search(page) or CLAIMS_PATTERN.search(page):
                raise PaperSlidesError("slides.md cover page must not declare a content section or claims.")
        elif index == len(pages) - 1:
            closing_titles = re.findall(r"(?m)^######[ \t]+\S.*$", page)
            if "lastpage" not in classes or len(closing_titles) != 1:
                raise PaperSlidesError(
                    "slides.md last slide must use lastpage with exactly one non-empty H6 closing title."
                )
            if SECTION_PATTERN.search(page) or CLAIMS_PATTERN.search(page):
                raise PaperSlidesError("slides.md last page must not declare a content section or claims.")
            closing_body = re.sub(r"(?m)^######[ \t]+\S.*$", "", page, count=1)
            closing_body = COMMENT_PATTERN.sub("", closing_body)
            if HTML_TAG_PATTERN.search(closing_body):
                raise PaperSlidesError("slides.md last slide may contain only its H6 closing title.")
            closing_body = HTML_TAG_PATTERN.sub("", closing_body)
            if re.sub(r"\s+", "", unescape(closing_body)):
                raise PaperSlidesError("slides.md last slide may contain only its H6 closing title.")
        else:
            section_matches = [value.casefold() for value in SECTION_PATTERN.findall(page)]
            is_structural = bool(classes & STRUCTURAL_CLASSES)
            if is_structural and not section_matches:
                if CLAIMS_PATTERN.search(page):
                    raise PaperSlidesError(
                        f"slides.md structural page {page_number} must not declare claims without a section."
                    )
            else:
                if len(section_matches) != 1:
                    raise PaperSlidesError(
                        f"slides.md content page {page_number} requires exactly one section declaration."
                    )
                section = section_matches[0]
                section_counts[section] += 1
                section_sequence.append(section)
                if len(headings_h2) != 1:
                    raise PaperSlidesError(
                        f"slides.md content page {page_number} must contain exactly one H2 title."
                    )
                claims = page_claims(page, page_number)
                for claim_id in claims:
                    if claim_id not in claim_sections:
                        raise PaperSlidesError(
                            f"slides.md page {page_number} references unknown summary claim {claim_id}."
                        )
                    expected_prefix = SECTION_PREFIXES.get(section)
                    if expected_prefix and not claim_id.startswith(expected_prefix):
                        raise PaperSlidesError(
                            f"slides.md page {page_number} section {section} cannot cite {claim_id}."
                        )
                    referenced_claims.add(claim_id)
        if VISIBLE_CLAIM_PATTERN.search(COMMENT_PATTERN.sub("", page)):
            raise PaperSlidesError(
                f"slides.md page {page_number} exposes summary claim ids; keep them in <!-- claims: ... -->."
            )

        if classes & LAYOUT_CLASSES:
            layout_pages += 1
        inspector = SlideHTMLInspector()
        inspector.feed(page)
        inspector.close()
        page_placeholder_ids: set[str] = set()
        for placeholder in inspector.placeholders:
            figure_id = placeholder["figure_id"]
            if figure_id not in figure_catalog:
                raise PaperSlidesError(
                    f"slides.md page {page_number} placeholder references unknown {figure_id or 'figure'}."
                )
            if placeholder["source_locator"] not in figure_catalog[figure_id]["source_locators"]:
                raise PaperSlidesError(
                    f"slides.md page {page_number} placeholder locator does not resolve for {figure_id}."
                )
            if not set(placeholder["classes"]) & IMAGE_PANEL_CLASSES:
                raise PaperSlidesError(
                    f"slides.md page {page_number} figure-placeholder must use an image panel class."
                )
            if not placeholder["has_number_node"] or not placeholder["has_caption_node"]:
                raise PaperSlidesError(
                    f"slides.md page {page_number} placeholder requires number and caption nodes."
                )
            if figure_id not in placeholder["text"]:
                raise PaperSlidesError(
                    f"slides.md page {page_number} placeholder must visibly display {figure_id}."
                )
            expected_caption = " ".join(str(figure_catalog[figure_id]["caption"]).split())
            if placeholder["caption_text"] != expected_caption:
                raise PaperSlidesError(
                    f"slides.md page {page_number} caption does not exactly match {figure_id} context."
                )
            expected_asset = figure_assets.get(figure_id)
            if expected_asset is not None:
                expected_path = str(expected_asset["path"])
                if placeholder["image_sources"] != [expected_path]:
                    raise PaperSlidesError(
                        f"slides.md page {page_number} placeholder for {figure_id} must embed its "
                        f"prepared source asset: {expected_path}."
                    )
            page_placeholder_ids.add(figure_id)
            referenced_figures.add(figure_id)
            placeholder_count += 1

        # A paper caption may cite another figure (for example, "Row 1 ... in
        # Figure 3"). That cross-reference is not a visible figure panel on
        # this page, so exclude caption nodes before checking visible mentions.
        page_without_captions = FIGURE_CAPTION_NODE_PATTERN.sub("", page)
        page_figure_ids = {
            normalize_figure_id(token)
            for token in FIGURE_REFERENCE_PATTERN.findall(page_without_captions)
        }
        unknown_figures = sorted(page_figure_ids - set(figure_catalog))
        if unknown_figures:
            raise PaperSlidesError(
                f"slides.md page {page_number} references unknown figures: {', '.join(unknown_figures)}."
            )
        missing_placeholders = sorted(page_figure_ids - page_placeholder_ids)
        if missing_placeholders:
            raise PaperSlidesError(
                f"slides.md page {page_number} references figures without placeholders: "
                + ", ".join(missing_placeholders)
                + "."
            )

        markdown_images = [
            match.group(1).split()[0]
            for match in MARKDOWN_IMAGE_PATTERN.finditer(COMMENT_PATTERN.sub("", page))
        ]
        css_media = [match.group(2).strip() for match in CSS_URL_PATTERN.finditer(page)]
        html_images = inspector.image_sources
        media_references = [*markdown_images, *css_media, *html_images]
        image_reference_count += len(markdown_images) + len(html_images)
        for reference in media_references:
            validate_media_reference(workspace, reference, page_number)
        page_metrics.append({"page": page_number, **validate_page_capacity(page, page_number)})

    ranks = [SECTION_ORDER.index(section) for section in section_sequence]
    if ranks != sorted(ranks):
        raise PaperSlidesError("slides.md sections must progress background -> method -> experiments -> takeaways.")
    for required, minimum in (("background", 1), ("method", 2), ("experiments", 1)):
        if section_counts[required] < minimum:
            raise PaperSlidesError(
                f"slides.md requires at least {minimum} {required} content page(s)."
            )
    if section_counts["method"] < max(section_counts["background"], section_counts["experiments"]):
        raise PaperSlidesError("slides.md must keep Method at least as detailed as Background and Experiments.")
    if layout_pages < 2:
        raise PaperSlidesError("slides.md must use VSP-Marp multi-panel layouts on at least two pages.")
    if figure_catalog and placeholder_count == 0:
        raise PaperSlidesError("slides.md must include at least one placeholder from the Figure catalog.")
    missing_claim_families = [
        prefix for prefix in ("B", "M", "E") if not any(claim.startswith(prefix) for claim in referenced_claims)
    ]
    if missing_claim_families:
        raise PaperSlidesError(
            "slides.md must cite background, method, and experiment claim families; missing: "
            + ", ".join(missing_claim_families)
            + "."
        )

    return {
        "page_count": len(pages),
        "section_page_counts": section_counts,
        "layout_page_count": layout_pages,
        "claim_reference_count": len(referenced_claims),
        "referenced_claim_ids": sorted(referenced_claims),
        "figure_placeholder_count": placeholder_count,
        "image_reference_count": image_reference_count,
        "referenced_figure_ids": sorted(referenced_figures),
        "page_metrics": page_metrics,
    }


def validate_slides(
    workspace: Path,
    *,
    paper_id: str,
    source_format: str,
    source_fingerprint: str,
    read_output_fingerprint: str,
    summary_output_fingerprint: str,
) -> JsonObject:
    directory = Path(workspace)
    slides_path = directory / SLIDES_FILE
    if not slides_path.is_file():
        raise PaperSlidesError(f"{SLIDES_FILE} is missing.")
    context, context_fingerprint = validate_slides_context(
        directory,
        paper_id=paper_id,
        source_format=source_format,
        source_fingerprint=source_fingerprint,
        read_output_fingerprint=read_output_fingerprint,
        summary_output_fingerprint=summary_output_fingerprint,
    )
    report = validate_slides_document(
        directory,
        slides_path.read_text(encoding="utf-8"),
        context,
    )
    return {
        "slides_fingerprint": sha256_file(slides_path),
        "metadata": {
            "slides_context_schema": SLIDES_CONTEXT_SCHEMA,
            "slides_context": SLIDES_CONTEXT_FILE,
            "slides_context_fingerprint": context_fingerprint,
            "theme": THEME_NAME,
            "theme_fingerprint": context["presentation"]["theme_fingerprint"],
            "math": "katex",
            "size": "16:9",
            **report,
        },
    }


def run_marp_smoke(workspace: Path) -> JsonObject:
    with tempfile.TemporaryDirectory(prefix="mary-marp-smoke-") as temporary:
        output = Path(temporary) / "slides.html"
        runner = _render_marp_html(Path(workspace), output, purpose="Optional Marp smoke compile")
    return {"status": "passed", "runner": runner}


def _marp_command() -> list[str]:
    marp = shutil.which("marp")
    if marp:
        return [marp]
    npx = shutil.which("npx")
    if npx is None:
        raise PaperSlidesError("Marp rendering requires marp or npx on PATH.")
    return [npx, "--offline", "--yes", "@marp-team/marp-cli@4.3.1"]


def _render_marp_html(
    workspace: Path,
    output: Path,
    *,
    purpose: str,
    bare: bool = False,
) -> str:
    directory = Path(workspace)
    slides_path = directory / SLIDES_FILE
    command = _marp_command()
    arguments = [
        *command,
        "--config-file",
        str(MARP_CONFIG_PATH),
        str(slides_path),
        "--allow-local-files",
    ]
    if bare:
        arguments.extend(["--template", "bare"])
    arguments.extend(["--output", str(output)])
    completed = subprocess.run(
        arguments,
        cwd=directory,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=90,
        check=False,
    )
    if completed.returncode != 0 or not output.is_file():
        detail = " ".join((completed.stderr or completed.stdout).split())[-500:]
        raise PaperSlidesError(f"{purpose} failed: {detail or 'no output'}")
    return Path(command[0]).name


def _slide_image_reference_count(text: str) -> int:
    count = len(MARKDOWN_IMAGE_PATTERN.findall(COMMENT_PATTERN.sub("", text)))
    inspector = SlideHTMLInspector()
    inspector.feed(text)
    inspector.close()
    return count + len(inspector.image_sources)


def _find_chromium() -> str:
    for executable in ("chromium", "chromium-browser", "google-chrome", "google-chrome-stable"):
        resolved = shutil.which(executable)
        if resolved:
            return resolved
    raise PaperSlidesError(
        "Image overflow audit requires Chromium or Google Chrome on PATH; audit was not skipped."
    )


def _browser_probe(html_path: Path) -> tuple[JsonObject, str]:
    chromium = _find_chromium()
    node = shutil.which("node")
    if node is None:
        raise PaperSlidesError("Image overflow audit requires Node.js on PATH; audit was not skipped.")
    if not IMAGE_OVERFLOW_BROWSER_PROBE_PATH.is_file():
        raise PaperSlidesError("Bundled image overflow browser probe is missing.")
    try:
        completed = subprocess.run(
            [
                node,
                str(IMAGE_OVERFLOW_BROWSER_PROBE_PATH),
                chromium,
                html_path.resolve().as_uri(),
            ],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=40,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise PaperSlidesError(
            "Chromium image overflow audit timed out after 40 seconds; audit was not skipped."
        ) from exc
    if completed.returncode != 0:
        detail = " ".join(completed.stderr.split())[-500:]
        raise PaperSlidesError(f"Chromium image overflow audit failed: {detail or 'no output'}")
    if not completed.stdout.strip():
        raise PaperSlidesError(
            "Chromium image overflow audit produced no measurement result; audit was not skipped."
        )
    try:
        payload = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        raise PaperSlidesError("Chromium image overflow audit returned invalid JSON.") from exc
    if not isinstance(payload, dict):
        raise PaperSlidesError("Chromium image overflow audit returned an invalid result object.")
    if payload.get("error"):
        raise PaperSlidesError(f"Chromium image overflow audit failed: {payload['error']}")
    return payload, Path(chromium).name


def build_image_overflow_report(
    payload: JsonObject,
    *,
    slides_fingerprint: str,
    marp_runner: str,
    browser_runner: str,
) -> JsonObject:
    raw_records = payload.get("records")
    if not isinstance(raw_records, list):
        raise PaperSlidesError("Image overflow audit result is missing records.")
    per_image: list[JsonObject] = []
    for raw in raw_records:
        if not isinstance(raw, dict):
            raise PaperSlidesError("Image overflow audit contains an invalid image record.")
        slide_rect = raw.get("slide_rect")
        image_rect = raw.get("image_rect")
        if not isinstance(slide_rect, dict) or not isinstance(image_rect, dict):
            raise PaperSlidesError("Image overflow audit record is missing bounding boxes.")
        try:
            overflow = {
                "left": max(0.0, float(slide_rect["left"]) - float(image_rect["left"])),
                "right": max(0.0, float(image_rect["right"]) - float(slide_rect["right"])),
                "top": max(0.0, float(slide_rect["top"]) - float(image_rect["top"])),
                "bottom": max(0.0, float(image_rect["bottom"]) - float(slide_rect["bottom"])),
            }
            image_width = float(image_rect["width"])
            image_height = float(image_rect["height"])
        except (KeyError, TypeError, ValueError) as exc:
            raise PaperSlidesError("Image overflow audit bounding box is malformed.") from exc
        overflow = {key: round(value, 2) for key, value in overflow.items()}
        max_overflow = max(overflow.values(), default=0.0)
        loaded = bool(raw.get("loaded")) and image_width > 0 and image_height > 0
        if not loaded or max_overflow > IMAGE_OVERFLOW_FAIL_PX:
            status = "fail"
        elif max_overflow > IMAGE_OVERFLOW_REVIEW_PX:
            status = "review"
        else:
            status = "ok"
        per_image.append(
            {
                "page": int(raw.get("page") or 0),
                "src": str(raw.get("src") or ""),
                "loaded": loaded,
                "overflow": overflow,
                "max_overflow_px": round(max_overflow, 2),
                "status": status,
            }
        )
    failed = [item for item in per_image if item["status"] == "fail"]
    review = [item for item in per_image if item["status"] == "review"]
    return {
        "status": "failed" if failed else "passed",
        "slides_fingerprint": slides_fingerprint,
        "canvas": {"width": 1280, "height": 720},
        "thresholds_px": {
            "review_above": IMAGE_OVERFLOW_REVIEW_PX,
            "fail_above": IMAGE_OVERFLOW_FAIL_PX,
        },
        "marp_runner": marp_runner,
        "browser_runner": browser_runner,
        "total_slides": int(payload.get("total_slides") or 0),
        "total_images": len(per_image),
        "review_images": review,
        "failed_images": failed,
        "per_image": per_image,
    }


def run_slide_image_overflow_audit(workspace: Path) -> JsonObject:
    directory = Path(workspace)
    slides_path = directory / SLIDES_FILE
    text = slides_path.read_text(encoding="utf-8")
    slides_fingerprint = sha256_file(slides_path)
    expected_images = _slide_image_reference_count(text)
    if expected_images == 0:
        return {
            "status": "passed",
            "slides_fingerprint": slides_fingerprint,
            "canvas": {"width": 1280, "height": 720},
            "thresholds_px": {
                "review_above": IMAGE_OVERFLOW_REVIEW_PX,
                "fail_above": IMAGE_OVERFLOW_FAIL_PX,
            },
            "marp_runner": "not-required",
            "browser_runner": "not-required",
            "total_slides": 0,
            "total_images": 0,
            "review_images": [],
            "failed_images": [],
            "per_image": [],
        }
    if not IMAGE_OVERFLOW_AUDIT_SCRIPT_PATH.is_file():
        raise PaperSlidesError("Bundled image overflow audit script is missing.")
    with tempfile.TemporaryDirectory(prefix=".mary-image-overflow-", dir=directory) as temporary:
        html_path = Path(temporary) / "slides.html"
        marp_runner = _render_marp_html(
            directory,
            html_path,
            purpose="Marp image overflow render",
            bare=True,
        )
        html = html_path.read_text(encoding="utf-8")
        marker = "</body>"
        head_marker = "<head>"
        if marker not in html or head_marker not in html:
            raise PaperSlidesError("Marp image overflow render produced malformed HTML.")
        base = f'<base href="{directory.resolve().as_uri()}/">'
        html = html.replace(head_marker, f"{head_marker}{base}", 1)
        audit_script = IMAGE_OVERFLOW_AUDIT_SCRIPT_PATH.read_text(encoding="utf-8")
        html_path.write_text(html.replace(marker, f"<script>{audit_script}</script>{marker}", 1), encoding="utf-8")
        payload, browser_runner = _browser_probe(html_path)
    report = build_image_overflow_report(
        payload,
        slides_fingerprint=slides_fingerprint,
        marp_runner=marp_runner,
        browser_runner=browser_runner,
    )
    if report["total_images"] != expected_images:
        raise PaperSlidesError(
            "Image overflow audit measured "
            f"{report['total_images']} rendered images but slides.md declares {expected_images}."
        )
    if report["failed_images"]:
        details = "; ".join(
            f"page {item['page']} {item['src'] or '(empty src)'} "
            f"max={item['max_overflow_px']}px loaded={item['loaded']}"
            for item in report["failed_images"][:5]
        )
        raise PaperSlidesError(f"Image overflow audit failed: {details}")
    return report
