#!/usr/bin/env python3
"""Generate command entrypoints and phase snapshots from maintained sources.

This operates on the skill checkout, never a user's project bundle. Projects
receive a versioned runtime/prompt bundle through explicit runtime operations.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
from collections.abc import Sequence

CONTRACT_VERSION = "3.0"
COMMAND_SKILLS = {
    "mw-init": "init",
    "mw-plan": "plan",
    "mw-run": "run",
    "mw-status": "status",
    "mw-stop": "stop",
    "mw-debug": "debug",
    "mw-cycle": "cycle",
    "mw-learn": "lecture-learning",
    "mw-exam": "exam-review",
    "mw-review": "exam-review",
    "slide-learning": "slide-to-lecture",
    "mw-paper": "paper",
    "mw-notion": "notion",
}
PHASE_NAMES = (
    "mw-init", "mw-plan", "mw-ready", "mw-resume", "mw-execute",
    "mw-review", "mw-debug", "mw-learn", "mw-exam", "slide-learning",
)
GENERATED_MARKER = "<!-- Generated by scripts/mw_surfaces.py; do not edit."


def skill_parts(path: Path) -> tuple[str, str]:
    """Read the deliberately small scalar metadata used by command skills."""
    source = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\n(.*?)\n---\n(.*)\Z", source, re.DOTALL)
    if not match:
        raise ValueError(f"{path}: expected YAML frontmatter")
    fields = {}
    for key in ("name", "description"):
        item = re.search(rf"^{key}:\s*(.+)$", match.group(1), re.MULTILINE)
        if not item:
            raise ValueError(f"{path}: nonempty {key} required")
        value = item.group(1).strip()
        if value.startswith('"') and value.endswith('"'):
            value = json.loads(value)
        elif value.startswith("'") and value.endswith("'"):
            value = value[1:-1].replace("''", "'")
        if not value or value in ("|", ">"):
            raise ValueError(f"{path}: {key} must be a nonempty scalar")
        fields[key] = value
    return fields["description"], match.group(2).strip() + "\n"


def generated_header(source: str, body: str) -> str:
    digest = hashlib.sha256(body.encode()).hexdigest()
    return (
        f"{GENERATED_MARKER}\n"
        f"Source: {source}\nContract: {CONTRACT_VERSION}\n"
        f"Source SHA-256: {digest}\n-->\n\n"
    )


def expected_outputs(root: Path) -> dict[Path, str]:
    outputs = {}
    for command, skill in COMMAND_SKILLS.items():
        relative = f"skills/{skill}/SKILL.md"
        source = root / relative
        description, _ = skill_parts(source)
        alias = " This is a compatibility alias for `/mw-exam`." if command == "mw-review" else ""
        # Commands intentionally only route to the maintained skill. They do not
        # duplicate its procedure or create a third set of instruction rules.
        body = (
            f"# /{command}\n\n"
            f"Load `{relative}` from this installed Mary Workflow skill bundle and "
            f"follow it for the user's request.{alias}\n\n"
            "Treat `$ARGUMENTS` as user input, not a shell command. Preserve the "
            "user's scope and existing authorization.\n"
        )
        outputs[root / f"commands/{command}.md"] = (
            "---\ndescription: " + json.dumps(description, ensure_ascii=False)
            + "\nargument-hint: \"[request]\"\n---\n\n"
            + generated_header(relative, source.read_text(encoding="utf-8")) + body
        )
    for name in PHASE_NAMES:
        relative = f"references/phases/{name}.md"
        source = (root / relative).read_text(encoding="utf-8")
        outputs[root / f".mary-workflow/prompts/{name}.md"] = generated_header(relative, source) + source
    return outputs


def generate(root: Path, *, check: bool = False) -> list[str]:
    """Return drift paths; --check performs no writes, including directory creation."""
    outputs = expected_outputs(root)
    drift = []
    for path, expected in outputs.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            drift.append(str(path.relative_to(root)))
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected, encoding="utf-8")
    # Generated entrypoints removed from the map must disappear on regeneration;
    # unrelated files are never removed.
    for folder in ("commands", ".mary-workflow/prompts"):
        for path in (root / folder).glob("*.md"):
            if path not in outputs and GENERATED_MARKER in path.read_text(encoding="utf-8"):
                drift.append(str(path.relative_to(root)))
                if not check:
                    path.unlink()
    return sorted(drift)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report stale outputs without changing files")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1], help="skill checkout root")
    args = parser.parse_args(argv)
    try:
        drift = generate(args.root.resolve(), check=args.check)
    except (OSError, ValueError) as exc:
        parser.exit(2, f"surface generation failed: {exc}\n")
    if drift:
        print(("Stale" if args.check else "Generated") + " surfaces:\n" + "\n".join(drift))
    else:
        print("Generated surfaces match maintained sources.")
    return 1 if args.check and drift else 0


if __name__ == "__main__":
    raise SystemExit(main())
